### ISSUE TITLE
Helm deployment container permissions issues with Redis

### ISSUE THREAD

**Issue by wallnerryan** [bitnami/bitnami-docker-redis#100]
**Description**

Helm deployment container permissions issues with Redis

helm --debug install stable/redis --set persistence.enabled=false

Everything seems to go fine, but the POD logs show.

`EACCES: permission denied, open '/.nami/registry.json' `

**Steps to reproduce the issue:**

1. Follow this cluster setup https://gist.github.com/wallnerryan/735775b9da55519c28b7fc78458735ef
2. kubectl create serviceaccount --namespace kube-system tiller
3. kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
4. helm init --service-account tiller
5. helm --debug install stable/redis --set persistence.enabled=false

**Describe the results you received:**
`EACCES: permission denied, open '/.nami/registry.json' `

**Describe the results you expected:**
Redis to start without permissions issues.

**Additional information you deem important (e.g. issue happens only occasionally):**
1.9.0 Kubernetes with cri-containerd anc CNI

**Version**
1.9.0
- Output of `docker version`:
NONE - uses cri-containerd
```
@worker-0:~$ cri-containerd version
1.0.0-beta.1

```

- Output of `docker info`:

```
(see above)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Using GCP, Ubuntu VMs

**Comment by tompizmor** [comment]
@wallnerryan, could you please let me know the exact redis chart version that you are installing? You can see it with the `helm list` command.
I don't have the same cluster setup but I am unable to reproduce the issue in minikube or gke.

**Comment by wallnerryan** [comment]
@tompizmor i believe this has to do with running kubelet with
```
 --container-runtime=remote \\
  --container-runtime-endpoint=unix:///var/run/cri-containerd.sock \\
```

I was using `https://github.com/containerd/cri-containerd/releases/download/v1.0.0-beta.1/cri-containerd-1.0.0-beta.1.linux-amd64.tar.gz` as the runtime instead of docker. 

Im re-installing k8s with docker this time, and will try again. Not sure how many people have tried to run helm on https://github.com/kelseyhightower/kubernetes-the-hard-way but it sets that up by default

**Comment by tompizmor** [comment]
OK! Please let me know if you find something else!

**Comment by wallnerryan** [comment]
Thanks @tnextday, this was originally opened with kubernetes 1.9.0 and i havent tried yet with 1.10.2 and containerd or 1.11. It may have been fixed by now. What versions of containerd/kubernetes did you use?

**Comment by tnextday** [comment]
kubernetes: v1.11.0
containerd: v1.1.2

**Comment by tompizmor** [comment]
Indeed the wrong gid and groups permissions when using containerd will make Redis fail for wrong permissions.

As Redis is a non-root container by default, the permissions are configured for the `root` group instead for a specific user. As @tnextday says, running the container as root is the workaround until containerd sets gid and group fine.

**Comment by justincormack** [comment]
You can put the explicit group you want here https://github.com/bitnami/bitnami-docker-redis/blob/master/4.0/Dockerfile#L24 eg `USER 1001:0` to spell out the group.

**Comment by juan131** [comment]
Hi @justincormack 

Did you try that solution? Were you able to successfully create a custom image and create a container choosing a custom group? AFAIK, the container won't initialise successfully..

**Comment by prydonius** [comment]
I think it makes sense to change https://github.com/bitnami/bitnami-docker-redis/blob/master/5.0/debian-9/Dockerfile#L29 to `USER 1001:0` as @justincormack suggests to always ensure we get gid 0.

> Please note that ownership and permissions configuration could not be properly set if you modify the group as you suggested.

@juan131 not sure what you mean, I built the image with this change and it works for me.

**Comment by juan131** [comment]
Hi @prydonius 

> @juan131 not sure what you mean, I built the image with this change and it works for me.

The image changed a lot since my last comment. Now it uses Bash logic and the initialisation it's not exactly the same. Therefore, it's very likely it's not a problem anymore.

> I think it makes sense to change https://github.com/bitnami/bitnami-docker-redis/blob/master/5.0/debian-9/Dockerfile#L29 to USER 1001:0 as @justincormack suggests to always ensure we get gid 0.

What do you think about this change @javsalgar @tompizmor ?

**Comment by prydonius** [comment]
FYI someone ran into this issue in Kubeapps with the MongoDB image when trying to run it on GKE with containeros which uses a version of containerd that doesn't yet have this fix. More context here: https://kubernetes.slack.com/archives/C9D3TSUG4/p1541092007002500

**Comment by juan131** [comment]
Hi @prydonius 

I'm not sure if it's the same issue that someone reported with Monocular: https://github.com/bitnami/bitnami-docker-mongodb/issues/115

It's an issue about MongoDB so please let's try to continue the discussion there to avoid confusion.

**Comment by wild-endeavor** [comment]
was this ever resolved?  Or do i need to rebuild the image specifying the group still?

**Comment by juan131** [comment]
Hi @wild-endeavor 

What version of **K8s** and **containerd** are you using? 

Did you face any issue install the Redis Helm chart on K8s? It's configured by default to set the proper securityContext and you shouldn't face any issue with the user running the containers.
