### ISSUE TITLE
Documentation example with incorrect environment variable

### ISSUE THREAD

**Issue by aosti** [bitnami/bitnami-docker-redis#102]
**Steps to reproduce the issue:**

1. I created a dockercomposer file using the example from Step 2: Create the replication slave in the link https://hub.docker.com/r/bitnami/redis/

**Describe the results you received:**
The slave could not connect to the master.

**Describe the results you expected:**
The slave connects successfully to the master.

**Additional information you deem important (e.g. issue happens only occasionally):**
The environment variable is set incorrectly for the redis-slave. The value is REDIS_MASTER_HOST=redis-primary, but it should be REDIS_MASTER_HOST=redis-master.  If I change this configuration, everything works ok.

**Version**

- Output of `docker version`: 

```
Docker version 17.12.1-ce, build 7390fc6
```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-37-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.853GiB
Name: bc
ID: A5YH:4DL7:QZSV:FXZM:T3P2:LNRI:4RCO:Y624:SXYX:BC3M:VGJF:TQJ6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown

```

**Comment by juan131** [comment]
Hi @aosti 

Thanks for reporting the issue on the **README**.md file. I just updated it in the internal repo which generates those files.

Once a new version/revision of Redis is released it will be automatically fixed. Let's keep the issue opened until then.
