### ISSUE TITLE
How to config redis sentinel in replication mode？

### ISSUE THREAD

**Issue by daiing** [bitnami/bitnami-docker-redis#107]
as title

**Comment by javsalgar** [comment]
We have a redis-sentinel container, did you check it? https://github.com/bitnami/bitnami-docker-redis-sentinel

**Comment by daiing** [comment]
thanks

**Comment by ermeaney** [comment]
I just dropped a PR at [142](https://github.com/bitnami/bitnami-docker-redis/pull/142) which adds support for replicas to find their master via sentinel

**Comment by javsalgar** [comment]
Thank you!!
