### ISSUE TITLE
password with ampersand bug 4.0.11

### ISSUE THREAD

**Issue by naseemkullah** [bitnami/bitnami-docker-redis#112]
password containing ampersand gets unwillingly interpolated into something else in redis.conf line 288 
as of 4.0.11

**Steps to reproduce the issue:**

1. Choose a redis password that contains an ampersand
2. deploy redis using the redis helm chart with image 4.0.11
3. Watch it break

**Comment by naseemkullah** [comment]
Ah, regex strikes again!

Very good find and thank you @juan131! 

I'll await the fix. :)

**Comment by juan131** [comment]
Hi @naseemkullah 

We just released a new revision of this Docker Image (**4.0.11-r27**) that should fix the issue with the special characters: `?`, `&` and `\`. Please feel free to use it and let us know if it's working as expected.

**Comment by naseemkullah** [comment]
Tried it out and it works as expected. Thanks for the prompt fix!
