### ISSUE TITLE
Error executing 'postInstallation': EEXIST: file already exists, symlink '/opt/bitnami/redis/conf' -> '/opt/bitnami/redis/etc'

### ISSUE THREAD

**Issue by tonglv** [bitnami/bitnami-docker-redis#118]
kubectl logs pod/gitlab-redis-6fd4bb6fc6-5tv9z    

Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing redis
Error executing 'postInstallation': EEXIST: file already exists, symlink '/opt/bitnami/redis/conf' -> '/opt/bitnami/redis/etc'

----------------------
#docker info
Containers: 9
 Running: 8
 Paused: 0
 Stopped: 1
Images: 38
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true

please support!  thanks!

**Comment by tonglv** [comment]
@juan131 
bitnami/redis:3.2.9-r2

**Comment by juan131** [comment]
Hi @tonglv 

As you might find at [Notable Changes](https://github.com/bitnami/bitnami-docker-redis#notable-changes) section, we changed significantly this image on version **4.0.1-r24**

Could you please upgrade your image following the instructions described on that section? I think you won't find the issue anymore using the latest image.

**Comment by tonglv** [comment]
@juan131 
# docker pull bitnami/redis:4.0.1-r24
Error response from daemon: manifest for bitnami/redis:4.0.1-r24 not found

pull successfully
docker pull bitnami/redis:4.0.11-r24

but ....
[root@kubernetes-110 ~]# kubectl logs pod/gitlab-redis-77c47b84fb-v584v
Error from server (BadRequest): container "gitlab-redis" in pod "gitlab-redis-77c47b84fb-v584v" is waiting to start: ContainerCreating
[root@kubernetes-110 ~]# kubectl logs pod/gitlab-redis-77c47b84fb-v584v

Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues

mv: cannot move '/opt/bitnami/redis/etc/redis-default.conf' to a subdirectory of itself, '/opt/bitnami/redis/etc/redis.conf'

**Comment by juan131** [comment]
You need to use a container such a **busybox** to mount the persistent volume that has your Redis data (mount it at **/tmp/redis**) and run the commands:

```
find /tmp/redis/data -maxdepth 1 -exec mv {} /tmp/redis \;
rm -rf /tmp/redis/{data,conf,.initialized}
```

Then, as you can find in the Notable change section, it is also necessary to change the MountPoint:

```
# Change the mount point
sed -i -e 's#redis_data:/bitnami/redis#redis_data:/bitnami/redis/data#g' docker-compose.yml
```

If you're using Kubernetes, you need to ensure that `redis_data` is being mounted at **/bitnami/redis/data**, could you check you're using the right mountPoint at your `gitlab-redis` deployment/statefulset?

**Comment by tonglv** [comment]
@juan131  
thanks

**Comment by juan131** [comment]
Hi @tonglv 

Could you update the image following that steps?
