### ISSUE TITLE
[feature request] adding a way to load redis module

### ISSUE THREAD

**Issue by tuananh** [bitnami/bitnami-docker-redis#124]
ref: https://github.com/helm/charts/pull/7745#issuecomment-437283606

**Comment by juan131** [comment]
Hi @tuananh 

Thanks for opening the issue. Just to provide more information for other users.

Redis can load new modules by running the command below:

```
redis-cli -a YOURPASSWORD MODULE LOAD /path/to/the/module.so
```

It's possible to mount the corresponding modules to be loaded using a volume (via Docker Volume or PV on K8s) and then it's just necessary to run the command above so they're loaded on Redis.

This image should support a way to load any module the user wants to use during the initialisation of the container.

**Comment by juan131** [comment]
I think we could implement a solution such as the one we used on MariaDB: https://github.com/bitnami/bitnami-docker-mariadb#initializing-a-new-instance

The user could mount its modules at `/docker-entrypoint-initdb.d` (or any other path) so every module mounted there its loaded on Redis during the initialisation.

What do you think @tuananh @tompizmor ?

**Comment by tuananh** [comment]
that would be rather convenient!

**Comment by juan131** [comment]
Hi @tuananh 

I just created a task and included it in our backlog. It will be considered for future application versions.

Thanks for bringing this up!

**Comment by tuananh** [comment]
Many thanks

**Comment by Aravindumasankar** [comment]
Has this been implemented?

**Comment by juan131** [comment]
It hasn't been implemented yet @Aravindumasankar 

There's an internal opened task but we didn't have time to work on that yet. We'll notify you on this thread as soon as we release an image including this feature.

**Comment by 2ZZ** [comment]
Also interested in this :)

**Comment by miguelaeh** [comment]
Hi, 
We notice there are a lot of people interested on this. We will implement it as soon as possible and we will notify all of you on this thread.

**Comment by advaidya** [comment]
@miguelaeh @juan131 Any update on this..We too have a requirement to load modules on top of bitnami.  I am new to docker as well as kube but will be willing to contribute if I get right set of directions on this.

**Comment by juan131** [comment]
Hi @advaidya 

There is a PR I created a long time ago (see https://github.com/bitnami/bitnami-docker-redis/pull/134) but I forgot about it. Sorry for that.

I'll try to resume the work and come up with a solution.

**Comment by advaidya** [comment]
Thanks @juan131

**Comment by singhvivek2503** [comment]
Hello,

Is this implemented yet?

**Comment by juan131** [comment]
I am afraid it's not @singhvivek2503 . I created an uncompleted PR several months ago, but I didn't find the time to finish it. I'd try book some time to work on it.

**Comment by bangonkali** [comment]
any news on this? Been wanting to use something like redisearch myself.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, there are not news on this.

**Comment by igorbrigadir** [comment]
I also wanted this for rejson, ended up using this workaround: https://github.com/bitnami/bitnami-docker-redis/issues/92#issuecomment-387036095 (Editing the Dockerfile and including the module there, pushing custom docker image to a private repo and using that instead, eg: https://github.com/bitnami/bitnami-docker-redis/compare/master...recsyslabs:master )

**Comment by juan131** [comment]
Thanks @igorbrigadir 

That workaround is similar to the one another user suggested in the link below:

- https://github.com/bitnami/charts/issues/2917#issuecomment-649989134

Extending the image has always been a possibility of addressing this issue, although ideally we should provide a way to do it dynamically without needing to extend it.

**Comment by donovanvanheerden** [comment]
Hi, any news on this? Interested in trying RedisSearch and RedisJSON.

**Comment by juan131** [comment]
We don't have any knews. That said, there was a user that shared a possible workaround for this, see https://github.com/bitnami/charts/issues/2917#issuecomment-649989134 as I mentioned in my previous message.

**Comment by ancgate** [comment]
Thanks, @juan131  for your hard work. I see you've created already a PR to fix this issue. Was this fixed in the PR?

**Comment by juan131** [comment]
Hi @ancgate 

That PR is still open since I never find the time to work on it, I'd appreciate if anybody else resume the work there and finish it.

**Comment by ancgate** [comment]
Can we schedule a meeting so that you can give me some guidance on this? I can send you an email as well. Let me know.

**Comment by juan131** [comment]
Hi @ancgate 

I'm afraid we do not provide live support nor live guidance on how to contribute to our repositories. The Dockerfile, all the scripts and configuration files used to create this image are available in this repository for inspection.

We do have a Contributing Guidelines, see:

- https://github.com/bitnami/bitnami-docker-redis/blob/master/CONTRIBUTING.md

**Comment by ancgate** [comment]
Thanks @juan131. I will work on this.

**Comment by y0zong** [comment]
> Hi @tuananh
> 
> Thanks for opening the issue. Just to provide more information for other users.
> 
> Redis can load new modules by running the command below:
> 
> ```
> redis-cli -a YOURPASSWORD MODULE LOAD /path/to/the/module.so
> ```
> 
> It's possible to mount the corresponding modules to be loaded using a volume (via Docker Volume or PV on K8s) and then it's just necessary to run the command above so they're loaded on Redis.
> 
> This image should support a way to load any module the user wants to use during the initialisation of the container.

hi I use this image in my project and I‘m try to load redisgraph module in the way your suggested but it's not work
here is my docker file, I add mode loader in config file 

*overrides.conf*
```
loadmodule /bitnami/redis/redisgraph.so
```
*docker-compose.yml*
```
volumes:
      - ./overrides.conf:/bitnami/redis/mounted-etc/overrides.conf
      - ./redisgraph.so:/bitnami/redis/redisgraph.so
```

 here is the error 

``` bash 
1:M 14 Mar 2022 11:50:33.007 # Module /bitnami/redis/redisgraph.so failed to load: libgomp.so.1: cannot open shared object file: No such file or directory
```
it seems docker can't load **redisgraph.so** or */bitnami/redis/* does't have permissions to load it

please help

**Comment by carrodher** [comment]
Please note this comment was posted almost 4 years ago, probably now the configuration is different. Can you please create a separate issue with your specific use case to avoid mixing topics and reopening old conversations? Thanks
