### ISSUE TITLE
ARMv8 support

### ISSUE THREAD

**Issue by coder543** [bitnami/bitnami-docker-redis#130]
I was playing around with Amazon's [new ARM-based EC2 instances](https://aws.amazon.com/blogs/aws/new-ec2-instances-a1-powered-by-arm-based-aws-graviton-processors/) and noticed that while the official Redis docker image supports ARMv8, bitnami's doesn't.

I don't have a strong opinion here, especially since I don't know how much effort this would take, but I just wanted to raise awareness of this issue.

**Comment by javsalgar** [comment]
Hi,

Thanks for the suggestion. I don't think we have short term plans to include this architecture in our containers. However, in case we decide going for ARMv8 containers, I will update this ticket.
