### ISSUE TITLE
Use of custom config file 

### ISSUE THREAD

**Issue by sido420** [bitnami/bitnami-docker-redis#137]
**Description**
This may be a usage question I want to use secret file as config file.

I've already tried the following in compose file:
    command: cat /run/secrets/config > /opt/bitnami/redis/etc/redis.conf && /run.sh

but it fails.

**Version**

- Output of `docker version`:

```
Version:           18.06.1-ce
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.0, build c8524dc1 
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Physical

**Comment by javsalgar** [comment]
Hi

You can mount a custom configuration file without changing the command. The container logic allows that.

https://phabricator.nami.run/T14884

**Comment by sido420** [comment]
yup I've seen that .. this is related to https://github.com/bitnami/bitnami-docker-redis/issues/138 so I'm closing it.
