### ISSUE TITLE
Root Pwd Env Var required after first use

### ISSUE THREAD

**Issue by sido420** [bitnami/bitnami-docker-redis#138]
**Description**
I understand the requirement of specifying Root Pwd environment variable the first time container starts. But, why is it required every time the container is started? 
Also, cant requirepass Redis config param be used to set password? If yes, which environment vars would be required if we use requirepass

**Steps to reproduce the issue:**

1. Start container with REDIS_PASSWORD=<pwd>
2. Stop container
3. Run container again but this time removing the environment var

**Describe the results you received:**
```The REDIS_PASSWORD Environment variable is empty or not set ...```

**Describe the results you expected:**
Container should run at least after the first time.

**Comment by sido420** [comment]
The idea is that I don't like using Redis password in docker compose/.env files. So, I'd start the container first time with pwd then remove it from compose file and restart. I can share compose files with others without exposing any passwords this way.

See https://docs.docker.com/engine/swarm/secrets/ for use cases of secrets. And above all it should be the standard way of providing secrets/pwds etc to containers. IIIRC there is a separate issue open for providing password in secret files, so if there are no issues, I'd rather suggest putting the whole config file (with requirepass) in a secret file.

**Comment by javsalgar** [comment]
In our redis chart, that information is stored in secrets. Our docker-compose files here are meant for testing purposes. In a production environment, we recommend using our chart. Regarding docker-swarm, I do not have that experience using secrets. Do you have an example file so we can see how it would be done?
