### ISSUE TITLE
latest helm chart - slave pod readiness prob check fails

### ISSUE THREAD

**Issue by niemyjski** [bitnami/bitnami-docker-redis#141]
`
Readiness probe failed: Warning: Using a password with '-a' option on the command line interface may not be safe. Warning: Using a password with '-a' option on the command line interface may not be safe. Error: Connection reset by peer
`

The pod seems fine otherwise with the last message of: `* Ready to accept connections`

**Comment by niemyjski** [comment]
5.3.0 . We tried on AKS with and without a password and both had pod failures. We also had issues with no password and the master node. We moved to 5.2.0 and most issues went away. I think there are lots of issues with the current release (see upvotes and comments on the last commit.

**Comment by juan131** [comment]
There a couple of issues opened about the current version **5.0.3**:

https://github.com/helm/charts/issues/10733
https://github.com/helm/charts/issues/10769

Could you check them?

@javsalgar is working on fixing them both on https://github.com/helm/charts/pull/10826

Hopefully we can have the solution available very soon and we'll release a new version of the chart.

**Comment by carrodher** [comment]
This issue should be solved in the mentioned PRs, please, feel free to reopen it if needed.
