### ISSUE TITLE
Manifest for 4.0.8-r3 missing from Docker Hub

### ISSUE THREAD

**Issue by rvdh** [bitnami/bitnami-docker-redis#144]
**Description**
We use [Weaveworks Flux](https://github.com/weaveworks/flux/) to automatically deploy new versions of docker images onto our infrastructure. Flux downloads a list with available images from Docker Hub, but is unable to do so for the Bitnami Redis image, because the information about the tag is missing:

```
ts=2019-05-15T06:42:12.067036051Z caller=warming.go:198 component=warmer info="refreshing image" image=docker.io/bitnami/redis tag_count=1450 to_update=1 of_which_refresh=0 of_which_missing=1
ts=2019-05-15T06:42:12.185716199Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/bitnami/redis auth={map[]} warn="manifest for tag 4.0.8-r3 missing in repository docker.io/bitnami/redis" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2019-05-15T06:42:12.185795332Z caller=warming.go:206 component=warmer updated=docker.io/bitnami/redis successful=0 attempted=1
```
You can also see this on the Docker Hub page:
https://hub.docker.com/r/bitnami/redis/tags?page=57 (the pagenumber might be incorrect when you're reading this, if new tags have been pushed in the meantime). Where it's supposed to list the image size, it says 'Unavailable'.

Please re-push the tag to the repository or remove it from Docker Hub :)

**Comment by juan131** [comment]
Thanks so much for reporting this issue @rvdh 

I don't know what happened with that specific tag, but I'm afraid we'll need to remove that tag from DockerHub.

**Comment by juan131** [comment]
Hi @rvdh 

Just a quick update to let you know the tag has been removed.

**Comment by rvdh** [comment]
Great! Thanks. 👍
