### ISSUE TITLE
entrypoint related issue with docker.io/bitnami/redis:5.0.5

### ISSUE THREAD

**Issue by MahajanTushar** [bitnami/bitnami-docker-redis#145]
/entrypoint.sh: line 25: exec: --: invalid option  

The above mentioned error is seen while running the docker container, the docker image is docker.io/bitnami/redis:5.0.5. Please give some wayout to solve this.

![redis issue](https://user-images.githubusercontent.com/36584534/59409839-dead6700-8dd4-11e9-88c8-f14ee1cef4de.PNG)

**Comment by rafariossaa** [comment]
Hi @MahajanTushar ,
  You need to change the order of de parameters:

```
$ docker run -p 6379:6379 --env ALLOW_EMPTY_PASSWORD=yes -it bitnami/redis:latest

Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting Redis setup **
....
```

Best regards,
Rafael Rios Saavedra

**Comment by MahajanTushar** [comment]
Thanks for the help, actually I am trying to run the same on kubernetes in following way -

kubectl run --namespace redis knotted-rat-redis-client --rm --tty -i --restart='Never' \ --env REDIS_PASSWORD=v3ChKhASI2 \ --image docker.io/bitnami/redis:5.0.5 -- bash

and it is generating likewise error.
Here the format seems to be okay. Can you suggest any changes ?

**Comment by rafariossaa** [comment]
Hi,
That worked for me:

```
$ kubectl run --namespace default  redis-client --rm --tty -i --restart='Never' --env REDIS_PASSWORD=password --image docker.io/bitnami/redis:5.0.5 -- bash
If you don't see a command prompt, try pressing enter.
I have no name!@redis-client:/$ redis-cli --version
redis-cli 5.0.5
I have no name!@redis-client:/$
```
I used a different namespace but that shouldn't cause any problem.

Could you recheck the command you are running ? Also maybe it is related to the kubectl version you are using. You can check the order of the parameters with `$ kubectl run --help`. 

Best regards,
Rafael Rios Saavedra
