### ISSUE TITLE
Pod deletion for StatefulSet of redis cluster doesn't restore the cluster-state of redis

### ISSUE THREAD

**Issue by MahajanTushar** [bitnami/bitnami-docker-redis#146]
I have used redis:5.0.1-alpine in my statefulset, the stateful set has 6 pods and the redis cluster formation is done using below command

redis-cli --cluster create {IPlist is placed here} --cluster-replicas 1

Now in case the pods get accidentally deleted or the AKS gets out of service, then the pods when create after AKS resumes will have different IP.

I tried by deliberately deleting the pods, when the pods get recreated then the cluster state changes to "fail" ( which was "ok" when the cluster was initially created)

Also when I try to get the old data set into cluster, a message appears telling that "cluster is down"

I have displayed the code for redis.conf file used for cluster creation

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
  namespace: redis
data:
  update-node.sh: |
    #!/bin/sh
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0- 
    9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
  redis.conf: |+
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
```

![redis error](https://user-images.githubusercontent.com/36584534/59490146-927c2880-8ea1-11e9-93c7-228bdc7b39ee.PNG)
![redis-error 2](https://user-images.githubusercontent.com/36584534/59490147-9314bf00-8ea1-11e9-8885-2c0e814d7708.PNG)

In the second snapshot, it can be seen that the rediscluster is retaining the POD IPs which are of deleted and the new POD IPs are different. This is also a concern.

Please suggest how this could be fixed

**Comment by alemorcuq** [comment]
Hi, @MahajanTushar.

> I have used redis:5.0.1-alpine in my statefulset, the stateful set has 6 pods and the redis cluster formation is done using below command

Note that `redis:5.0.1-alpine` is not a Bitnami image, so I don't know how can we help you. Did you post it here by mistake maybe?

Regards,
Alejandro

**Comment by MahajanTushar** [comment]
okay, I was thinking that the behavior might be synonymous, so posted it.
