### ISSUE TITLE
Trojan Xmrig in image

### ISSUE THREAD

**Issue by IlyaVorozhbit** [bitnami/bitnami-docker-redis#150]
redis:
    image: 'bitnami/redis:latest'

So, I know that in official redis:latest image a security breach (you can check here: https://hub.docker.com/_/redis?tab=tags), but I supposed that your images (of bitnami) is okey. 

https://yadi.sk/i/gi1XwGx__7vjLA

Thank you very much

**Comment by miguelaeh** [comment]
Hi @IlyaVorozhbit ,
Thank you very much for reporting, could you give more information about how did you find what is shown in the image? I cannot get it.

**Comment by IlyaVorozhbit** [comment]
@miguelaeh I had misconfigured docker-compose redis service, I exposed port 6379. Now I had fixed it, and have no problems. Sorry
