### ISSUE TITLE
Can't open the append-only file: Permission denied

### ISSUE THREAD

**Issue by Seifon** [bitnami/bitnami-docker-redis#152]
```
xm-redis          |  16:53:20.25 
xm-redis          |  16:53:20.25 Welcome to the Bitnami redis container
xm-redis          |  16:53:20.25 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
xm-redis          |  16:53:20.25 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
xm-redis          |  16:53:20.26 Send us your feedback at containers@bitnami.com
xm-redis          |  16:53:20.26 
xm-redis          |  16:53:20.26 INFO  ==> ** Starting Redis setup **
xm-redis          |  16:53:20.27 INFO  ==> Initializing Redis...
xm-redis          |  16:53:20.28 INFO  ==> ** Redis setup finished! **
xm-redis          | 
xm-redis          |  16:53:20.28 INFO  ==> ** Starting Redis **
xm-redis          | 1:C 19 Oct 2019 16:53:20.294 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
xm-redis          | 1:C 19 Oct 2019 16:53:20.294 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
xm-redis          | 1:C 19 Oct 2019 16:53:20.294 # Configuration loaded
xm-redis          | 1:M 19 Oct 2019 16:53:20.295 # Can't open the append-only file: Permission denied
```

**Comment by andresbono** [comment]
Hi @Seifon, can you give us more details on how are you launching this image?

**Comment by hootnot** [comment]
Hi, having the same issue. Started it as the README says under Persistence:

```
sudo docker run -e ALLOW_EMPTY_PASSWORD=yes -v /home/vagrant/var/Redis:/bitnami/redis/data bitnami/redis:latest
```

/home/vagrant/var/Redis is an empty directory

**Comment by andresbono** [comment]
Hi @hootnot, thanks for sharing your solution. The idea behind all this is that the user with uid `1001` inside the container should be able to write to `/bitnami/redis/data`.

You can for instance do:

```
sudo chown 1001 /home/vagrant/var/Redis
sudo docker run -e ALLOW_EMPTY_PASSWORD=yes -v /home/vagrant/var/Redis:/bitnami/redis/data bitnami/redis:latest
```

**Comment by hootnot** [comment]
@andresbono, yes I noticed that 1001 later when I entered the container by shell

Config and database location by using `-v <src>:<dst>` working fine now.

Maybe a small update to the README regarding the 1001 ?

**Comment by andresbono** [comment]
Where do you suggest to update it? In this section: [Persisting your database](https://github.com/bitnami/bitnami-docker-redis#persisting-your-database)?. Would you like to open a PR?

**Comment by rahbal** [comment]
```
redis 09:01:58.40 INFO  ==> ** Starting Redis **
1:C 01 Feb 2021 09:01:58.419 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 01 Feb 2021 09:01:58.419 # Redis version=6.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 01 Feb 2021 09:01:58.419 # Configuration loaded
1:M 01 Feb 2021 09:01:58.421 # Can't open the append-only file: Permission denied
```

Still facing same issue on default bitnami/redis chart.

**Comment by andresbono** [comment]
Hi @rahbal, can you give us more details on how are you launching this image? Please check this:  https://github.com/bitnami/bitnami-docker-redis/issues/152#issuecomment-545378098.

**Comment by rahbal** [comment]
@andresbono I solved it, I was using pv and pvc, so setting 

```
volumePermissions:
  enabled: true
```

worked fine. Thank you.

**Comment by andresbono** [comment]
Perfect, @rahbal!! Thanks for letting us know.

**Comment by zaf187** [comment]
@rahbal did you manage to get it running after that? after i added the volumePermissions, i got an error in the init container this time showing this message;
`chown: changing ownership of '/data': Operation not permitted`

did you get anything similar?

**Comment by yanqiw** [comment]
> @rahbal did you manage to get it running after that? after i added the volumePermissions, i got an error in the init container this time showing this message; `chown: changing ownership of '/data': Operation not permitted`
> 
> I have the same use case as you, my own pv and pvc. The pv is an nfs host path volume. did you get anything similar?

I solve this by below values.yaml
```yaml
master:
  podSecurityContext:
    fsGroup: 1000  # your nfs folder owner group
  containerSecurityContext:
    runAsUser: 1000 # your nfs folder owner uid
# volumePermissions:  # no need this
#   enabled: true
```

**Comment by jimi-pz** [comment]
https://hub.docker.com/r/bitnami/redis - 'Configuration file' section explains how default configuration can be overwritten in **docker-compose** file. But this leads to above error; can someone have a solution that we can apply in **docker-compose** file ?

**Comment by imami** [comment]
Try `-e REDIS_AOF_ENABLED=no` in your `docker run` command, 
or alternatively  use :
```
services:
  redis:
  ...
    environment:
      - REDIS_AOF_ENABLED=no
  ...
```

Ref:
https://github.com/bitnami/bitnami-docker-redis#disabling-aof-persistence

**Comment by rafariossaa** [comment]
@jimi-pz Could you give it a try to what @imami indicated ?

**Comment by jimi-pz** [comment]
It did not work. Here is my sample docker-compose file; 

version: '3.8'

services:
  redis:
    image: docker.io/bitnami/redis:latest
    container_name: redis-server
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_AOF_ENABLED=no
    volumes:
      - ./containers/redis/config/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - redis_data:/bitnami/redis/data
    ports:
      - 6379:6379
    networks:
      - foo_network
      
networks:
  foo_network:
    driver: bridge

volumes:
  redis_data:
    driver: local

![image](https://user-images.githubusercontent.com/1504259/152755731-4dfd65a0-3500-4aeb-9dda-20e72ee98a5e.png)

**Comment by rafariossaa** [comment]
@jimi-pz 
As yours is more docker related, do you mind opening a new issue so we can help you properly ?.
Thanks forehand.

**Comment by jimi-pz** [comment]
[https://github.com/bitnami/bitnami-docker-redis/issues/231](url)
