### ISSUE TITLE
Slave Error /bin/bash: line 20: /run.sh: No such file or directory

### ISSUE THREAD

**Issue by canalptekin** [bitnami/bitnami-docker-redis#153]
I am using Pivotal Kubernetes and helm version as follows.
![Screen Shot 2019-10-30 at 10 49 42](https://user-images.githubusercontent.com/38102300/67838710-fc206a80-fb02-11e9-848c-3a33fedbcf78.png)

When I use helm yaml "values-production.yaml",  master node is running, but the slave node returns  following error.
![Screen Shot 2019-10-30 at 10 53 55](https://user-images.githubusercontent.com/38102300/67838972-9385bd80-fb03-11e9-8de6-18276c4bbd5d.png)
I removed ready image and although I use https://hub.docker.com/r/bitnami/redis/dockerfile image, the same error continues.

**Comment by juan131** [comment]
Hi @canalptekin 

I'm unable to reproduce your issue using the [values-production.yaml](https://github.com/helm/charts/blob/master/stable/redis/values-production.yaml) locally using Minikube.

What version of the `stable/redis` chart are you using? Is it the latest (current version `9.5.0`)? You can check it by running the command below:

```console
$ helm search stable/redis
```

If that's not the case, could you update your Helm repo by running the command below and retry?

```console
$ helm repo update
```
