### ISSUE TITLE
Add 6.0-rc1 tag

### ISSUE THREAD

**Issue by andreastoyota** [bitnami/bitnami-docker-redis#155]
6.0-rc1 came out. Would be great to use it.

**Comment by andresbono** [comment]
Hi @andreastoyota, thanks for filling the issue. We only track and maintain stable releases but not beta or release candidate versions. As soon as the 6.0 reaches stable, we will start the process to include it.

**Comment by andreastoyota** [comment]
6.0 has now been released, can we re-open this ticket?
