### ISSUE TITLE
[feature request] add ssl support

### ISSUE THREAD

**Issue by moebius87** [bitnami/bitnami-docker-redis#157]
I often use [redis-stunnel](https://github.com/Runnable/redis-stunnel) as a _sidecar_ to have a secure connection but it would be great if the functionality were integrated into the bitnami redis image.

see also: 
https://www.redislabs.com/blog/stunnel-secure-redis-ssl/

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feature request! We are planning to do a refactor of the redis chart, which could also add the support of ssl via the extravolume mounts and custom configuration. Pinging @carrodher for consideration.

**Comment by carrodher** [comment]
I will take it into account, thanks

**Comment by carrodher** [comment]
Not stale, we're working on it

**Comment by kasmtech** [comment]
Your docker hub page states TLS is supported in redis 6 and provides instructions. So I'm confused as to whether it is supported or not. My attempts to use it per the instructions failed. The error indicated I needed to provide a CA cert, which I did. A CA cert should not be required if client cert auth is disabled, but I provided one anyway. I came here looking for support and found this open ticket for SSL support.

**Comment by carrodher** [comment]
Hi, yes, this issue should be closed as this feature is supported in Redis 6 as described [here](https://github.com/bitnami/bitnami-docker-redis#securing-redis-traffic). It was added in this commit https://github.com/bitnami/bitnami-docker-redis/commit/1ee001ca15aab0747223e637d715624306cada6d and released in the `6.0.4-debian-10-r6` version.

If you are having any specific issue with the SSL/TLS configuration, please, can you create a new issue providing as much information as possible to try to reproduce your use case?
Some information like the environment variables you're using, docker-compose, etc is really useful for use. Also, take into account if you're using the bitnami Redis chart, please open the issue in the bitnami/charts repo by clicking [here](https://github.com/bitnami/charts/issues/new/choose).
