### ISSUE TITLE
why use aof default？

### ISSUE THREAD

**Issue by zaozaoniao** [bitnami/bitnami-docker-redis#159]
I have create a cantainer from the  redis image,
 when I  'docker exec -it  .[containerid] '
 find the redis config:  /opt/bitnami/redis/etc/redis.conf

show:  no save command  for  snapshotting  , but have set the [appendonly yes] ?

》  The redis  offical snapshutting is the default persistence  mode.

**Comment by miguelaeh** [comment]
Hi @zaozaoniao ,
Could you elaborate the description? Where is that shown? What steps are you following?

**Comment by zaozaoniao** [comment]
1.  docker run --name redis -e ALLOW_EMPTY_PASSWORD=yes bitnami/redis:latest

2. 
![image](https://user-images.githubusercontent.com/5810880/78117978-e52acf00-7438-11ea-9a01-6e098e168eb7.png)

3. 
![image](https://user-images.githubusercontent.com/5810880/78118030-f5db4500-7438-11ea-9970-d674f2407f65.png)


4.  head  -n 699  /opt/bitnami/redis/etc/redis.conf
![image](https://user-images.githubusercontent.com/5810880/78118107-16a39a80-7439-11ea-88c4-d388ca6c86d4.png)

**Comment by beltran-rubo** [comment]
You can also overwrite the "appendonly" option adding that option in the "command" , see https://github.com/bitnami/bitnami-docker-redis/issues/160 

Would that work for you?

**Comment by zaozaoniao** [comment]
yes. I can use command to  override   or use  a local config to  replace the image config。

 but why the image use  aof default  ?

**Comment by beltran-rubo** [comment]
Well, it depends on your specific needs. 

We are using those containers in our Kubernetes solutions, Helm Charts https://github.com/bitnami/charts and that means that any pod (or redis process) can be killed at any time and start again a new one. For that specific scenario the AOF minimizes the chance of data loss. In any case, you can configure the container in different ways depending on your specific case.

**Comment by zaozaoniao** [comment]
1. I do not  think change the default  config is good. 
2. if the repo is  specify case,  the repo readme should show the  aof default

**Comment by beltran-rubo** [comment]
Thanks for your feedback, we will reevaluate that decision and make it more prominent in the readme.

**Comment by beltran-rubo** [comment]
We added a note in the README https://github.com/bitnami/bitnami-docker-redis#persisting-your-database

We will also work to make it easier to configure this parameter via ENV VAR.
