### ISSUE TITLE
Redis Master and Slave connection differents machine

### ISSUE THREAD

**Issue by RodrigoBCC** [bitnami/bitnami-docker-redis#161]
It's possible use redis slave and master in deferents instance and connect then? I woud like to make workes in separate instances.. How can a do it?

**Comment by RodrigoBCC** [comment]
Well, by default redis listens on 127.0.0.1 have you edited your redis.conf to include the line bind your.private.ip.address.
So it possible make a variable to allow_external_ip?

**Comment by miguelaeh** [comment]
Hi @RodrigoBCC ,
As you can see here: https://github.com/bitnami/bitnami-docker-redis/blob/master/5.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh
by default Redis is listening in all the interfaces:
```
redis_conf_set bind 0.0.0.0 # Allow remote connections
```

But I am afraid there is no option to use an external IP, you could to modify the container and add that option.
Could you provide more information about how are you trying to deploy it, so we can see if there is another option?

**Comment by RodrigoBCC** [comment]
Hi @miguelaeh ,
Yes, after a few days looking for answers i found one. 
To allow redis external connection ip it is necessary startup redis-server on terminal! After this, u can connect from another host. Like this:

`redis:
    # restart: always
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ****
`
I tried bind ip and did not work, u shoud make environment for redis-server or new image i don't know... 
Well, i trie make redis queue for celery, and my app have two instance to pass this queue  for both, 
by the way i did not test with u image, i will test after.

Thank u very much!

**Comment by miguelaeh** [comment]
Hi @RodrigoBCC ,
Thank you very much for sharing your solution, but I am afraid I am not sure yet about how are you deploying Redis, are you using docker-compose? 
Regarding the command, the container is actually executing the `redis-server` command So I don't see the difference between put it in the command and let the container initialize Redis.
