### ISSUE TITLE
Add 6.0 tag

### ISSUE THREAD

**Issue by andreastoyota** [bitnami/bitnami-docker-redis#166]
redis 6 has been released

**Comment by carrodher** [comment]
Thanks for letting us know, our team is going to work to test and release the Redis container images and Redis charts based on the new version. I can't give you an exact release date but we will update this issue when new versions are ready.

**Comment by andreastoyota** [comment]
bump

**Comment by beltran-rubo** [comment]
hi @andreastoyota the Redis version 6 has been already released in this repository. We also upgraded the Redis Helm Chart to use this new version as well https://github.com/bitnami/charts/tree/master/bitnami/redis.

**Comment by andreastoyota** [comment]
awesome - thanks!
