### ISSUE TITLE
Missing support for kubernetes 1.16

### ISSUE THREAD

**Issue by ericp96** [bitnami/bitnami-docker-redis#170]
**Description**
When installing bitnami/redis 10.6.3 you receive the following error:

```bash
no matches for kind "Deployment" in version "extensions/v1beta1"
```
This is due to the `Deployment` kind being moved top the `apps/v1` api resource.

**Steps to reproduce the issue:**

1. Install Kubernetes 1.16+ (Now the default in Docker Desktop)
2. `helm repo add bitnami https://charts.bitnami.com/bitnami`
3. `helm install bitnami/redis --version 10.6.13`

The error above is received.

**Describe the results you expected:**

The redis chart installs as expected

**Version**

|Kind | Version|
|---|---|
|OS|Mac 10.15.3|
|Docker Installation|Docker Desktop 2.3.0.2|
|Docker|19.03.8|
|Kubernetes|1.16+|

**Comment by javsalgar** [comment]
Hi,

As this is something related with charts, I will forward this to the bitnami/charts repository.

**Comment by javsalgar** [comment]
Let's continue the conversation here: https://github.com/bitnami/charts/issues/2585
