### ISSUE TITLE
How can i use this in my aspnet application, which I have deployed in AKS as a container in Pod

### ISSUE THREAD

**Issue by NirajCricket** [bitnami/bitnami-docker-redis#172]
I have deployed bitnami/redis cluster in aks
Now i want to know the steps of how i can add this in my webconfig for an aspnet mvc application.
hence my app can use it in aks

**Comment by joancafom** [comment]
Hi @NirajCricket !

Great to see you delve into the K8s world! Bitnami also offers a guide an information regarding several technological stacks. Here you have two that I think will come handy with Redis and AKS:

- [Bitnami Redis documentation](https://docs.bitnami.com/general/infrastructure/redis/ )
- [BItnami Getting starting guide in AKS](https://docs.bitnami.com/kubernetes/get-started-aks/ )

Hope those help, thanks!
