### ISSUE TITLE
What about the Transparent Huge Pages (THP) warning?

### ISSUE THREAD

**Issue by Kovah** [bitnami/bitnami-docker-redis#176]
**Description**

The container keeps logging a warning at the start regarding Transparent Huge Pages. I noticed this way back when using Redis 3 already but never had any issues regarding latency. Is this a huge problem? From what I can find on the web, there are mixed responses about the severity and actual impact on applications.
Some also state that this is a setting that must but change on the host.

**Steps to reproduce the issue:**

1. Start a recent version of the Bitnami 

**Describe the results you received:**

```
WARNING you have Transparent Huge Pages (THP) support enabled in your kernel.
This will create latency and memory usage issues with Redis. To fix this issue run the command 
'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local 
in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
```

**Describe the results you expected:**

No warnings are logged.

**Additional information you deem important (e.g. issue happens only occasionally):**

/

**Version**

Any recent Docker version

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Happens on both Linux servers as well as macOS Catalina.

**Comment by joancafom** [comment]
Hi @Kovah 

Thanks for you issue! You are right, this is something related to memory management and thus must be configure in the host machine (not the container itself). In case you are running Docker for Mac, you should modify this feature in Hyperkit (that is running a linux instance under the hood).

Regarding performance itself, you can assess it by yourself using the command `redis-benchmark` command from within the redis container. In my case, I have made two tests and can spot a slight improvement when disabling THP (and of course no more warnings were logged 😀).

In case you are curious about my the results I obtained (or If you do not want to run `redis-benchmark`), here you have the outputs.

[no_THP.txt](https://github.com/bitnami/bitnami-docker-redis/files/4879769/no_THP.txt)
[with_THP.txt](https://github.com/bitnami/bitnami-docker-redis/files/4879770/with_THP.txt)


Hope it helps, thanks!
