### ISSUE TITLE
cluster.externalAccess.enabled=true results in no workload being deployed

### ISSUE THREAD

**Issue by jonathon2nd** [bitnami/bitnami-docker-redis#181]
**Description**

Hello, I am attempting to deploy a Redis-Cluster in Rancher. Rancher runs on it's own management cluster, and I have another k8s cluster to run workloads. These are both run on a number of VM's. For networking, I have setup https://metallb.universe.tf/ which works for many other apps, including bitnami/redis. From the troubleshooting I have done, I do not think it is an issue with MetalLB, as it works for any other app I test it with, including bitnami/redis.

I am able to deploy and configure bitnami/redis without issue with MetalLB automatically working. I only experience this behavior when trying to deploy bitnami/redis-cluster. I have been working on this on and off for over a week now. I did not jump to the conclusion that it was a problem with bitnami/redis-cluster, I suspected everything else first. But I only have this problem with bitnami/redis-cluster. 

Any help would be greatly appreciated, I must be missing something.

**Steps to reproduce the issue:**

1. Ensure that `https://charts.bitnami.com/bitnami` is added to Catalogs.
2. In Rancher UI, navigate to k8s cluster apps, and select launch. 
3. Select Redis-Cluster from bitnami catalog.
4. Leave default values, including the latest template version 3.1.11.
5. Insert only one variable, `cluster.externalAccess.enabled=true`.
6. Launch the app.

**Describe the results you received:**

An application is launched, with networking fully setup, and no workload deployed. There is no attempt to deploy a workload.
![image](https://user-images.githubusercontent.com/52681917/90051355-2f507680-dc9d-11ea-8d5c-131e8d0eb9f8.png)
![image](https://user-images.githubusercontent.com/52681917/90051382-38d9de80-dc9d-11ea-9400-3844213975ad.png)

If `cluster.externalAccess.enabled` is then changed to `false`, and the application is redeployed, the networking is deleted, and the workload properly deployed. 
![image](https://user-images.githubusercontent.com/52681917/90052671-19dc4c00-dc9f-11ea-8c3d-13d386da3bb6.png)
![image](https://user-images.githubusercontent.com/52681917/90052694-252f7780-dc9f-11ea-994e-65af0dbcee1a.png)
![image](https://user-images.githubusercontent.com/52681917/90053089-9e2ecf00-dc9f-11ea-9f02-003e810f04b8.png)
![image](https://user-images.githubusercontent.com/52681917/90053104-a5ee7380-dc9f-11ea-9664-66c5d2f14b44.png)

**Describe the results you expected:**

What I expect to see is a deployed workload with networking, similar to when I deploy bitnami/redis with `master.service.type=LoadBalancer` and `networkPolicy.enabled=true`
![image](https://user-images.githubusercontent.com/52681917/90051619-90784a00-dc9d-11ea-9709-5d7d3831e1c7.png)
![image](https://user-images.githubusercontent.com/52681917/90051638-9a9a4880-dc9d-11ea-9f9f-a71d95e8423e.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

When I started working on this, it was possible to _trick_ the application into deploying a workload with the working network. I have one such cluster running right now, and as far as my testing can tell everything works as it should. I did this by flipping cluster.externalAccess.enabled from `false` to `true` to `false` a few times, and it would stick. I was not happy with this unpredictability and continued testing. At some point this behavior stopped happening and I was not able to trick a cluster into fully working again. Maybe caused by a reboot of the VM's. It still does not behave how it should, but at least it is predictable now. I have a working Redis-Cluster, but I can not reliably create another one. I can also assume any change to this cluster would result in either the workload or network being removed for some reason.

**Version**

- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 67
  Running: 37
  Paused: 0
  Stopped: 30
 Images: 26
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.13.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.49GiB
 Name: example.com
 ID: GDRH:MXK3:4V6C:XFHZ:C3IM:WKI4:FMRU:X6FE:RY4O:TZ7G:OQ6K:OCN4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Hi, I am not using rancher, but directly `kubectl`. I just installed the chart using `--set cluster.externalAccess.enabled=true` and it's true that there are no pods once finished the installation:
```console
$ helm install redis --set cluster.externalAccess.enabled=true bitnami/redis-cluster

#Wait some minutes

$ kubectl get pods
No resources found in default namespace.
```

Taking a look at the notes that appears during the initialization (you can also obtain them by running `helm get notes RELEASE_NAME`):
```console
$ helm get notes redis
** Please be patient while the chart is being deployed **

To get your password run:

    export REDIS_PASSWORD=$(kubectl get secret --namespace default redis-redis-cluster -o jsonpath="{.data.redis-password}" | base64 --decode)

To connect to your Redis server from outside the cluster check the following information:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w redis-redis-cluster'

    You will have a different external IP for each Redis node. Get the external ip from `-external` suffixed services: `kubectl get svc`.
    Redis port: 6379
    Once the LoadBalancerIPs are ready, you need to provide them and perform a Helm Upgrade:

    helm upgrade redis --set "cluster.externalAccess.enabled=true,cluster.externalAccess.service.type=LoadBalancer,cluster.externalAccess.service.loadBalancerIP[0]=load-balancerip-0,cluster.externalAccess.service.loadBalancerIP[1]=load-balancerip-1,cluster.externalAccess.service.loadBalancerIP[2]=load-balancerip-2,cluster.externalAccess.service.loadBalancerIP[3]=load-balancerip-3,cluster.externalAccess.service.loadBalancerIP[4]=load-balancerip-4,cluster.externalAccess.service.loadBalancerIP[5]=load-balancerip-5" bitnami/redis-cluster
    Where load-balancerip-i are the LoadBalancerIPs provided by the cluster.
```
taking a look at the last paragraphs it's needed an upgrade once the LoadBalancer IP is available in order to share this information with the different nodes. I followed those instructions and then
```console
$ kubectl get pods
NAME                                       READY   STATUS    RESTARTS   AGE
redis-redis-cluster-0                      1/1     Running   0          7m9s
redis-redis-cluster-1                      1/1     Running   0          7m8s
redis-redis-cluster-2                      1/1     Running   0          7m8s
redis-redis-cluster-3                      1/1     Running   0          7m8s
redis-redis-cluster-4                      1/1     Running   0          7m8s
redis-redis-cluster-5                      1/1     Running   0          7m8s
redis-redis-cluster-cluster-create-qq29n   1/1     Running   0          7m8s
```
all the pods are up and running. I am sorry about to provide those `kubectl` commands while you're using Rancher, but we are not used to working with Rancher, you should be able to translate the previous approach to some steps in the Rancher UI. In the same way, you can also obtain the `KUBECONFIG` from Rancher and use `kubectl`.

**Comment by jonathon2nd** [comment]
Thank you for the detailed and kind response. I completely glossed over this, and that was indeed what I missed. 

`Helm` does not get installed on the k8s cluster https://github.com/rancher/rancher/issues/14496 so running the command from Rancher UI console, or sshing into vm to run is not possible without modifying cluster. 

The following worked for me I think.
For Rancher UI, steps to resolve are as followed:
1. View the deployed app, and scroll down to services.
2. Note each IP that has been provisioned to each service by loadbalancer, in my case MetalLB.
3. Navigate to the top right and select upgrade.
![image](https://user-images.githubusercontent.com/52681917/90155991-92034a00-dd51-11ea-9140-c72056639469.png)

4. Add the variables at the bottom under `Answers`.
5. Upgrade.

After that, the workload was successfully deployed. 
![image](https://user-images.githubusercontent.com/52681917/90159793-8403f800-dd56-11ea-9fae-835aaf2a94bf.png)

What I am wondering now, is how the redis services become aware of the loadbalancer ip's. They seem to only be aware of their cluster ip's. I am wondering if that is going to be an issue for the client to receive new ip's in the event of a master failure.
Excerpt of redis-cli info
```
# Replication
role:master
connected_slaves:1
slave0:ip=10.42.3.0,port=6379,state=online,offset=560,lag=1
```

**Comment by jonathon2nd** [comment]
I see now, when I get info from one of the slaves, it contains the LB ip for the master.
```
# Replication
role:slave
master_host:10.1.0.109
master_port:6379
master_link_status:up
master_last_io_seconds_ago:4
```

Many thanks, once again!
