### ISSUE TITLE
Please add a way to set tcp-keepalive in config

### ISSUE THREAD

**Issue by diwu1989** [bitnami/bitnami-docker-redis#185]
I have a need to customize the redis instance with a non-default tcp-keepalive value.
Please expose this as a config env variable.

**Comment by FraPazGal** [comment]
Hello @diwu1989,

Thanks for opening this issue! Although there is no environment variable for changing the `tcp-keepalive` value, we give the option to mount a custom `redis.conf` file where you can indeed change that value. For more information, please read or [Configuration file](https://github.com/bitnami/bitnami-docker-redis#configuration-file) section.
