### ISSUE TITLE
Rename REDIS_REPLICATION_MODE=slave

### ISSUE THREAD

**Issue by asarkar** [bitnami/bitnami-docker-redis#187]
Starting with Redis 5, the word "slave" is being replaced by "replica". It'll be nice to keep up and rename `REDIS_REPLICATION_MODE=slave` to `REDIS_REPLICATION_MODE=replica`.
https://redis.io/commands/slaveof

**Comment by andresbono** [comment]
Thanks for raising this issue to our attention, @asarkar.

It looks like we are supporting the new naming for the replication mode. See:

https://github.com/bitnami/bitnami-docker-redis/blob/e09646eb162bc0ba1f87fc419f8c2d27ded62940/6.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh#L191

https://github.com/bitnami/bitnami-docker-redis/blob/e09646eb162bc0ba1f87fc419f8c2d27ded62940/6.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh#L264-L265


What seems to need an update is the `README.md` and the `docker-compose-replicaset.yaml` files. Would you like to contribute with a PR to modify those files? Contributions are more than welcome!

**Comment by asarkar** [comment]
@andresbono 
`sentinel masters` produces the following output:
```
31) "num-slaves"
32) "2"
33) "num-other-sentinels"
34) "2"
```

Is this coming from Redis or from the image? If the latter, line 31 should be renamed too for consistency.
