### ISSUE TITLE
User remap: Can't open append-only file: permission denied

### ISSUE THREAD

**Issue by LM1LC3N7** [bitnami/bitnami-docker-redis#188]
Hello,

I have an error when creating the container:  `Can't open the append-only file: Permission denied`.
I use the user remap option in docker, to be sure that a root user in a container is not root on the host.

--> I already tried to update permissions as explained on other issues, but it does not work, as a user id on the host is not the same user id on the container.

**Description**

**Steps to reproduce the issue:**

1. Change the docker configuration to use user remap.
```bash
{
    "selinux-enabled": true,
    "no-new-privileges": true,
    "userland-proxy": false,
    "userns-remap" : "default"
}         
```
2. Start the container with a volume for data retention (docker-compose):

```bash
  redis:

    image: bitnami/redis:6.0.9
    container_name: nextcloud-redis

    stdin_open: false
    tty: false
    restart: unless-stopped

    stop_grace_period: 15s
    stop_signal: SIGTERM

    environment:
      REDIS_PASSWORD: ${NEXTCLOUD_REDIS_PASSWORD}
      BITNAMI_DEBUG: "true"

    volumes:
      - /data/containers-data/nextcloud/redis:/bitnami/redis/data:z

    # Limit resources
    cpus: 1
    mem_limit: 2048m
    memswap_limit: 2048m

    networks:
      - nextcloud-backend
```

**Describe the results you received:**

```bash
nextcloud-redis | redis 16:18:06.19
nextcloud-redis | redis 16:18:06.20 Welcome to the Bitnami redis container
nextcloud-redis | redis 16:18:06.21 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
nextcloud-redis | redis 16:18:06.21 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
nextcloud-redis | redis 16:18:06.22
nextcloud-redis | redis 16:18:06.22 INFO  ==> ** Starting Redis setup **
nextcloud-redis | redis 16:18:06.27 DEBUG ==> Validating settings in REDIS_* env vars..
nextcloud-redis | redis 16:18:06.28 INFO  ==> Initializing Redis
nextcloud-redis | redis 16:18:06.29 DEBUG ==> Ensuring expected directories/files exist
nextcloud-redis | redis 16:18:06.34 INFO  ==> Setting Redis config file
nextcloud-redis | redis 16:18:06.43 INFO  ==> ** Redis setup finished! **
nextcloud-redis |
nextcloud-redis | redis 16:18:06.47 INFO  ==> ** Starting Redis **
nextcloud-redis | 1:C 23 Nov 2020 16:18:06.520 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
nextcloud-redis | 1:C 23 Nov 2020 16:18:06.520 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
nextcloud-redis | 1:C 23 Nov 2020 16:18:06.520 # Configuration loaded
nextcloud-redis | 1:M 23 Nov 2020 16:18:06.524 # Can't open the append-only file: Permission denied

```

**Describe the results you expected:**

Redis to start correctly.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:11 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 17
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  selinux
  userns
 Kernel Version: 4.18.0-193.28.1.el8_2.x86_64
 Operating System: CentOS Linux 8 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.54GiB
 Name: thor
 ID: W4VL:SZ2V:NL7G:YSWL:NXMX:RJJ5:DWF7:5A65:WPDN:PLNG:6UPH:SD6R
 Docker Root Dir: /data/docker/lib/231072.231072
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by FraPazGal** [comment]
Hello @LM1LC3N7!

From what I know, `userns-remap` is used to remap the root user that runs in the container to a non root user of the host machine to avoid a non-root access to get root privileges on the machine using a root container, is that right?

This container is already using a non-root user to run so you won't have that security issue. The `permission denied` error may be coming from the host folder owner not been the non-root user running the container, `1001`. To change the folder permissions, please try using:

```
$ chown 1001 -R /data/containers-data/nextcloud/redis
$ chmod 755 -R /data/containers-data/nextcloud/redis
```

**Comment by LM1LC3N7** [comment]
Thanks @FraPazGal for your message.

You are not right at 100%:
* Yes it remap the userid in the container
* No, not for root only but for all users

The container should start by `chown` and then start as non-root user to avoid this issue.
The other way is to know what ID will be set by Docker to correspond to the ID used in the container... But I don't know if this is possible.

**Comment by FraPazGal** [comment]
Hi @LM1LC3N7,

Yes, you are right, it would work with any type of user but I'm not sure if this is solving the `permission denied` error. That error should be caused by having wrong ownership in the host folder, did you have the chance to modifying those permissions using my steps above?

> The container should start by chown and then start as non-root user to avoid this issue.

I don't understand what you mean here. The container does a `chown/chmod` to the `1001` and then changes to that user in the build stage, is that what you are referring to?

> The other way is to know what ID will be set by Docker to correspond to the ID used in the container... But I don't know if this is possible.

Docker should be remapping the user container to the `dockremap` user by default, though you should be able to change that behaviour.

**Comment by LM1LC3N7** [comment]
Hello @FraPazGal,

> The container does a chown/chmod to the 1001 and then changes to that user in the build stage, is that what you are referring to?

Yes indeed. Thank you for the precision, I thought it wasn't the case.

I'm going to try again to apply the `dockremap` ID to the folder used by redis and will keep you informed.
I also tried to delete this folder to let docker create it and redis initialize it, but it didn't work.

**Comment by LM1LC3N7** [comment]
Hello again, 

Problem solved.

I have applied the `dockeremap` user ID on the shared folder **AND** updated permissions to allow group access (`chmod g+rwx <path>`).

Thanks for your answers, time and help!

**Comment by johnxy84** [comment]
If someone is facing this, this was what worked for me:
Instead of:
`command: redis-server --appendonly yes` 
I used:
`command: /opt/bitnami/scripts/redis/run.sh --appendonly yes`
