### ISSUE TITLE
error for naming rule

### ISSUE THREAD

**Issue by rampatnaik** [bitnami/bitnami-docker-redis#190]
Hello Redis

I am using  version=11.1.1 , the  Naming of redis doesnot work as per our project 
Name "name":"redis-A-B" not work , it work with "name":"redis-A"
I am using spinnaker , K8s: 17 version with  eks

error :
Error from server (Invalid): error when applying patch:
for: "STDIN": StatefulSet.apps "redis-A-B-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
Error from server (Invalid): error when applying patch:

**Comment by dani8art** [comment]
Hi @rampatnaik, you are modifying the name of a statefulset, this is not possible in k8s. It is not related to the docker image itself.

You can try to remove the statefulset and create again with a new name and it will work but you can't update it.
