### ISSUE TITLE
What is the group ID?

### ISSUE THREAD

**Issue by cneberg** [bitnami/bitnami-docker-redis#203]
Because of the complications of file permissions on volumes on the host OS.   What GID is the container running under? It appears its GID 0.   1) is that secure? 2) do you agree it won't change? 3) please document the GID used so its clear how implement them.

**Comment by Mauraza** [comment]
Hi @cneberg,

The bitnami/redis container is a non-root container. 
Could you check this part of the[ README.md](https://github.com/bitnami/bitnami-docker-redis#why-use-a-non-root-container)?
The user appears in the Dockerfile:
https://github.com/bitnami/bitnami-docker-redis/blob/501620187b48aae3d7e2afee28773ff6271cb261/6.2/debian-10/Dockerfile#L27

**Comment by cneberg** [comment]
I understand the userID is 1001.   I'm asking about the group ID.   it appears to be 0.

**Comment by cneberg** [comment]
https://docs.docker.com/engine/reference/builder/#user  
I guess the GID is 0 by default if not after the USER ID.

**Comment by Mauraza** [comment]
Hi @cneberg, 

> I guess the GID is 0 by default if not after the USER ID.

Yes, the GID is 0. 
```
$ ls -la /opt/bitnami/redis/
total 40
drwxrwxr-x 1 root root 4096 Jun 28 08:30 .
drwxrwxr-x 1 root root 4096 Jun 27 14:36 ..
drwxrwxr-x 1 root root 4096 Jun  1 16:39 bin
drwxrwxr-x 1 root root 4096 Jun 27 14:38 etc
drwxrwxr-x 1 root root 4096 Jun  1 16:39 licenses
drwxr-xr-x 2 1001 root 4096 Jun 28 08:30 logs
drwxr-xr-x 2 1001 root 4096 Jun 28 08:30 tmp
```
```
s$ getent group root | awk -F: '{printf "Group %s with GID=%d\n", $1, $3}'
Group root with GID=0
```
