### ISSUE TITLE
REDIS_PORT_NUMBER Documentation

### ISSUE THREAD

**Issue by zxlin** [bitnami/bitnami-docker-redis#205]
Not a particular bug/issue, but is there any reason that `REDIS_PORT_NUMBER` is not documented in the README? I was able to find it by viewing source, but the README led me to believe the existing `REDIS_MASTER_PORT_NUMBER` and `REDIS_REPLICA_PORT ` ENV variables would configure the redis server's listen port on a standalone deployment. 

Would a section on how to configure a simple standalone deployment be good to include?

Thought I give some feedback if that's helpful. Thanks for your work maintaining this!

**Comment by marcosbc** [comment]
Hi @zxlin, this would ideally be added into the [Configuration section](https://github.com/bitnami/bitnami-docker-redis#configuration), but for infrastructure container solutions we focus on practical examples on how to configure it (i.e. how to enable TLS).

In this case, maybe it would be worth adding a new example section of how to run Redis in a different port number. What do you think? Would you be up for contributing an improvement in the README with the suggested changes? Thanks!

**Comment by zxlin** [comment]
Of course!
