### ISSUE TITLE
 WARNING overcommit_memory is set to 0! 

### ISSUE THREAD

**Issue by masterwishx** [bitnami/bitnami-docker-redis#212]
Running Docker in Unraid
Having warning in log :

```
# WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
```
But filesystem is read only ?!?

**Comment by marcosbc** [comment]
Hi @masterwishx, if you see that warning, it means you most update the kernel settings.

However, note that since Docker uses the kernel of the host machine, you would need to update the kernel of your Unraid host (the one which runs the Docker container images).

**Comment by masterwishx** [comment]
OK, Thanks
i thouth its about vm size memory for redis docker ....

**Comment by marcosbc** [comment]
No problem!
