### ISSUE TITLE
When will the image of arm64 architecture be supported？

### ISSUE THREAD

**Issue by czhfe** [bitnami/bitnami-docker-redis#214]
When will the image of arm64 architecture be supported ?

**Comment by carrodher** [comment]
Hi, we created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
