### ISSUE TITLE
Use the newest release of wait-for-port

### ISSUE THREAD

**Issue by shrutimehta2812** [bitnami/bitnami-docker-redis#218]
bitnami/wait-for-port version v1.0 has go version 1.9 which has critical vulnerabilities. The master bitnami/wait-for-port has the version of go updated to v1.16 which fixes some of the vulnerabilities. 

I have raised an issue with bitnami/wait-for-port to create the new release from the latest master. 
Issue Ref: https://github.com/bitnami/wait-for-port/issues/6

I would like to request you to use the newer release of bitnami/wait-for-port whenever ready
(https://github.com/bitnami/bitnami-docker-redis/blob/4e6dd819700ea15dcd736489e2d3ca5cbf4b6cec/6.2/debian-10/Dockerfile#L12), so the updated version of Golang is available and some critical vulnerabilities can be fixed.

**Comment by jotamartos** [comment]
Hi @shrutimehta2812,

The latest version of the Bitnami Redis container includes a new version of the wait-for-port tool.

https://github.com/bitnami/bitnami-docker-redis/blob/bb98956915b3089660b64bd128b8fb1a5d9c8a4f/6.2/debian-10/Dockerfile#L12

Thank you for your time reporting this.

**Comment by shrutimehta2812** [comment]
Hi @jotamartos ,

Thank you for fixing the issue.
