### ISSUE TITLE
[question]Can I build a redis cluster with docker-compose.yml without creating a redis.conf file like "bitnami/bitnami-docker-mariadb"?

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [bitnami/bitnami-docker-redis#219]
Every time the host joins the Redis cluster, it needs to edit the configuration. This is very complicated. I don't know if there is any way to configure all these configurations in docker-compose. yml, just like your Mariadb Galera.Only one docker-compose.yml is required to deploy a cluster node.

**Comment by pablogalegoc** [comment]
Hi @Conmi-WhiteJoker,

You can use the [redis-cluster](https://github.com/bitnami/bitnami-docker-redis-cluster) image. It has a [docker-compose.yaml](https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml) to setup a five node cluster.

**Comment by Conmi-WhiteJoker** [comment]
> Hi @Conmi-WhiteJoker,
> 
> You can use the [redis-cluster](https://github.com/bitnami/bitnami-docker-redis-cluster) image. It has a [docker-compose.yaml](https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml) to setup a five node cluster.

Wow, this is really good. Thank you very much.

**Comment by pablogalegoc** [comment]
If you face any problems you can open an issue there and me or any of my teammates will help you with anything 🙂
