### ISSUE TITLE
[feature request] expose ACL_FILE env. variable

### ISSUE THREAD

**Issue by daveteu** [bitnami/bitnami-docker-redis#223]
### Request

other than `REDIS_PASSWORD` and other useful environment variables, is it possible to also expose `ACL_FILE` so we can easily set it to a file we want. (e.g. `/run/secrets/redis_acl`)

### Reason for this request
It's also a "configuration" file, by exposing it the env, it is easier to implement ACL rather than using custom redis.conf. ACL should be regarded as **essential** since it encourages security by letting apps use ACL user/password rather than root password.

### Currently.
We have to mount our own redis.conf file which means all the other environment variables like REDIS_REPLICATION_MODE, REDIS_PASSWORD, REDIS_MASTER_HOST etc become practically useless.

Using bitnami/redis in docker swarm environment.

**Comment by rafariossaa** [comment]
Hi,
  Is it not possible to set the env var using `docker run ... -e ACE_FILE="...."` or adding it in the environment section in the file `docker-compose.yml` ?

**Comment by daveteu** [comment]
> Hi,
> 
>   Is it not possible to set the env var using `docker run ... -e ACE_FILE="...."` or adding it in the environment section in the file `docker-compose.yml` ?
> 
> 

it needs to be exposed because it's currently commented out in the redis.conf. unless we create our own redis.conf. 

anyway, i added a sed script to command in docker-compose to replace with a custom acl instead of using custom redis.conf

**Comment by miguelaeh** [comment]
Hi @daveteu ,

> it needs to be exposed because it's currently commented out in the redis.conf. unless we create our own redis.conf.

I am not sure of that, the environment variable should take precedence over the configuration parameter. Also, if it is commented on the configuration file, it is not set, so it should also take the env var.

**Comment by daveteu** [comment]
currently if you just set ACL_FILE, it will not do anything to redis.conf. it will still be `# aclfile /etc/redis/users.acl`.

It's the reason why this bitnami/redis exist anyway right, it exposes useful environment variables which will be replaced in the redis.conf with its scripts. 

at this point in time ACL_FILE environment is not exposed. Which means it's not auto replaced in redis.conf, which is the reason of this feature request.

**Comment by miguelaeh** [comment]
Hi @daveteu ,
My fault, it seems like Redis does not support configuring the server using env vars. So yes, we would need to add that configuration to the container logic.
Would you like to create a PR?
