### ISSUE TITLE
ACL SAVE permission denied 

### ISSUE THREAD

**Issue by cdstg** [bitnami/bitnami-docker-redis#225]
**Description**

Hi I m using the  ACL file feature `/opt/bitnami/redis/mounted-etc/users.acl`

But if i run `ACL SAVE` I get `Opening temp ACL file for ACL SAVE: Permission denied`

`ACL LOAD` works fine

Someone mention that the tmp file saves to `/var/run/redis` but I cant test that out as I m unsure how to su on that minideb image

**Comment by juan131** [comment]
Hi @cdstg 

I guess you're manually exec'ing into the Redis container and running these commands using the `redis-cli` tool, am I right?
And.. I also guess that `users.acl` is a custom file you mounted [following these instructions](https://github.com/bitnami/bitnami-docker-redis#enabling-access-control-list), correct? Could you please share this custom file? I'd like to reproduce the same issue on my side.

**Comment by cdstg** [comment]
Yes using the redis-cli both external and inside the container 
and yes mounted as 
 environment:
      - REDIS_ACLFILE=/opt/bitnami/redis/mounted-etc/users.acl
    volumes:
      - /path/to/users.acl:/opt/bitnami/redis/mounted-etc/users.acl

After reading the https://github.com/redis/redis/blob/unstable/src/acl.c
I changed to mount the whole directory and made sure the directory is owed by 1001 
It now works as the temp file is created in there 

 environment:
      - REDIS_ACLFILE=/opt/bitnami/redis/mounted-etc/users.acl
    volumes:
      - /path/to/:/opt/bitnami/redis/mounted-etc/

**Comment by juan131** [comment]
Hi @cdstg 

That's great @cdstg !! I'm very glad that you were able to solve the issue by ensuring the permissions are compatible with this non-root container.

> Some more info also you must set the REDIS_PASSWORD even though its not used it is written to the config file. But ACL will take precedence. However, the bash script complains if its not set. I guess you could set the ALLOW_EMPTY_PASSWORD but i did not try it.

Correct, the container will complain if `ALLOW_EMPTY_PASSWORD=no` and the `REDIS_PASSWORD` is empty, regardless that you're using a custom ACL file or not.
