### ISSUE TITLE
Update README.md to explain what the difference is between version numbers

### ISSUE THREAD

**Issue by Pomax** [bitnami/bitnami-docker-redis#232]
### Name and Version

all of them

### What is the problem this feature will solve?

It is currently not clear whether the docker image numbers actually reflect the version of Redis itself. While it seems reasonable that they are, folks don't _know_ that they are unless the docs explicitly state this.

### What is the feature you are proposing to solve the problem?

Add a section to the readme called "Which version do I need?" or something, and then have a single paragraph explaining that docker images update in lockstep with Redis versions.

**Comment by javsalgar** [comment]
Hi,

The versioning of the containers does follow the exact versioning of Redis. Thank you so much for the input, I will let the folks of the documentation team know.
