### ISSUE TITLE
[feature or help] load module

### ISSUE THREAD

**Issue by y0zong** [bitnami/bitnami-docker-redis#233]
hi I use this image in my project and I‘m try to load redisgraph module in the way your suggested but it's not work
here is my docker file, I add mode loader in config file 

*overrides.conf*
```
loadmodule /bitnami/redis/redisgraph.so
```
*docker-compose.yml*
```
volumes:
      - ./overrides.conf:/bitnami/redis/mounted-etc/overrides.conf
      - ./redisgraph.so:/bitnami/redis/redisgraph.so
```

 when load redisgraph here is an error cuz *libgomp.so* is needed and more detail: [the system is missing the run-time dependency OpenMP. This can be installed on Ubuntu with apt-get install libgomp1, on RHEL/CentOS with yum install libgomp, and on OSX with brew install libomp](https://github.com/RedisGraph/RedisGraph/blob/master/README.md)

``` bash 
1:M 14 Mar 2022 11:50:33.007 # Module /bitnami/redis/redisgraph.so failed to load: libgomp.so.1: cannot open shared object file: No such file or directory
```

please help

_Originally posted by @y0zong in https://github.com/bitnami/bitnami-docker-redis/issues/124#issuecomment-1066717335_

**Comment by javsalgar** [comment]
Hi,

I'm afraid that, for this module, you may need to create a forked container that installs that missing system package. Depending on the module, it may require extra system packages not available in the image.
