### ISSUE TITLE
bitnami-docker-redis-stack (Helm Chart)

### ISSUE THREAD

**Issue by VagyokC4** [bitnami/bitnami-docker-redis#235]
### Name and Version

bitnami/bitnami-docker-redis

### What is the problem this feature will solve?

Ability to deploy the whole Redis Stack (Search, Graph, Time Series, Json, Bloom, Insights) using your helm chart.

### What is the feature you are proposing to solve the problem?

A new helm chart that specifically supports the use of  redis/redis-stack as the base redis image and exposing port 8001 for redis-insights, in addition to 6379 for the redis server.

### What alternatives have you considered?

I was able to replace the image with redis/redis-stack, and add the extraFlags, and I can get redis started with all its modules, but I'm not well versed enough to get the redis-insights port opened up.

For someone who knows what they are doing, I imagine this will be a pretty easy lift, as the current helm chart works with redis/redis-stack as the base image, when the extraFalgs are included: 
![image](https://user-images.githubusercontent.com/253250/160217849-3963df16-a20d-48be-8bcc-59645e10eec5.png)

The only thing missing would be exposing the redis-insights port, wired up internally on port 8001

Again, this is from my amateur POV, so I'm sure there might be more integrations that could make the helm chart more flexible / integrated with the redis/redis-stack image. e.g. the _ARGS variable inside the redis-stack image.

**Comment by rafariossaa** [comment]
Hi,
  This chart only support the use of Bitnami Images, to support redis-stack we should be producing our own image. This way we can keep track of the changes in the image and update the chart accordingly.

**Comment by VagyokC4** [comment]
> Hi, This chart only support the use of Bitnami Images, to support redis-stack we should be producing our own image. This way we can keep track of the changes in the image and update the chart accordingly.

👍 Awesome!  Can we do that please, as I'm sure I'm not the only one wanting to see this.   Redis Stack is the all-in-one platform for redis going forward, and it looks like it's really just the plug-in modules to redis that add the "extra" functionality.  So I would imagine the process is very similar to the redis package you produce now.  And the base image should probably be the redis/redis-stack-server image, as they say this is the one designed for production environments.

**Comment by rafariossaa** [comment]
I am adding this to our internal list of requests. However I can not tell if this will be created or when it would be created.

**Comment by K-Jo** [comment]
@rafariossaa If you do so, you'd need to find a way to align the versions correctly https://github.com/redis-stack/redis-stack/releases
