### ISSUE TITLE
Ability to read the reeds password from /run/secrets/REDIS_PASSWORD

### ISSUE THREAD

**Issue by sindre-nistad** [bitnami/bitnami-docker-redis#238]
### Name and Version

bitnami/redis:6.2.6

### What is the problem this feature will solve?

It would allow me to use secrets in docker compose, to easily synchronise them across services, and would allow me to is your image directly, without adding a custom startup script.

### What is the feature you are proposing to solve the problem?

I'd like the startup script (presumably `redis-env.sh`) to check if there is a file in `/run/secrets` (the default location of docker secrets) named `REDIS_PASSWORD` (same as the environment variable) and read it.

### What alternatives have you considered?

* Creating a separate startup script
* tweaking the command / entry point, so that the content of the file is added
* Setting some value for it (when running locally)

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Note that every env var has an equivalent `_FILE` version that allows you to point to the secret location. For example:

```
REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD
```

I believe that should cover your use case, right?

**Comment by sindre-nistad** [comment]
Thanks, that will work well
