### ISSUE TITLE
Default values are overiding the extra flags/values (REDIS_EXTRA_FLAGS)

### ISSUE THREAD

**Issue by njaisw** [bitnami/bitnami-docker-redis#239]
### Name and Version

bitnami/redis-cluster

### What steps will reproduce the bug?

Default  redis-default.conf is over-shadowing the values of the REDIS_EXTRA_FLAGS. If any common variable needs to be overridden, the  redis-default.conf values are overshadowing those values.

### What is the expected behavior?

REDIS_EXTRA_FLAGS should be set after default values.

### What do you see instead?

Not able to override any values in the redis-default.conf via  REDIS_EXTRA_FLAGS

**Comment by marcosbc** [comment]
Hi @njaisw, note that `REDIS_EXTRA_FLAGS` is meant to refer to CLI arguments to pass to `redis-server`, not configuration entries in the config files. As such, it is only affecting how the `redis-server` CLI command is started: https://github.com/bitnami/bitnami-docker-redis/blob/master/6.2/debian-10/rootfs/opt/bitnami/scripts/redis/run.sh
