### ISSUE TITLE
Release image for Redis 7.0

### ISSUE THREAD

**Issue by eduardobr** [bitnami/bitnami-docker-redis#242]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

Support latest major version of Redis, which became GA in April

### What is the feature you are proposing to solve the problem?

- Make Redis 7 available in stacksmith
- Include new image using Redis 7 in this repo

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we are working on it. As soon as there are news, we will let you know. cc @gongomgra

**Comment by carrodher** [comment]
The new version of this container was released some days ago, see https://github.com/bitnami/bitnami-docker-redis/commit/3216d74955ad1513a5239a422f7912de78f5bb27

There is still some work in progress for the Helm chart, but the containers are ready
