### ISSUE TITLE
Upgrade Base OS from minideb:buster to minideb:bullseye 

### ISSUE THREAD

**Issue by RaghuTrivandrum** [bitnami/bitnami-docker-redis#244]
### Name and Version

bitnami/redis:6.2.7-debian-10-r24

### What is the problem this feature will solve?

Hi Team,

We have observed some of the vulnerabilities are fixed in the latest Debian OS version. Here are the vulnerabilities scan result of both images
```
bitnami/minideb:bullseye (debian 11.3)
Total: 71 (UNKNOWN: 0, LOW: 60, MEDIUM: 1, HIGH: 9, CRITICAL: 1)

bitnami/minideb:buster (debian 10.12)
Total: 127 (UNKNOWN: 0, LOW: 83, MEDIUM: 11, HIGH: 24, CRITICAL: 9)
```
Can we use Debian version 11.3?

Thanks

### What is the feature you are proposing to solve the problem?

Upgrade Base OS from minideb:buster to minideb:bullseye

**Comment by anupamgupta13808** [comment]
Hi rafariossa,
Is there an ETA on when the new images might be released?

**Comment by carrodher** [comment]
Please note since some weeks ago all the images are using Debian 11 bullseye by default, see https://github.com/bitnami/bitnami-docker-redis#supported-tags-and-respective-dockerfile-links
