### ISSUE TITLE
After deploying pods on k8s from the image bitnami/redis it gives me error  /opt/bitnami/scripts/redis/entrypoint.sh: line 26: exec: --: invalid option

### ISSUE THREAD

**Issue by mhthaque** [bitnami/bitnami-docker-redis#246]
### Name and Version

bitnami/redis:latest

### What steps will reproduce the bug?

After deploying pods on k8s from the image bitnami/redis it gives me error

/opt/bitnami/scripts/redis/entrypoint.sh: line 26: exec: --: invalid option

### What is the expected behavior?

After deploying pods on k8s from the image bitnami/redis it gives me error

/opt/bitnami/scripts/redis/entrypoint.sh: line 26: exec: --: invalid option

06:12 PM  ✔ root on sfo-caas-man01 Δ [sfo-harbor] ⎈  kubectl -n sfo-harbor logs redis-674b56b45b-ztgwq -c redis
redis 01:12:17.59
redis 01:12:17.59 Welcome to the Bitnami redis container
redis 01:12:17.59 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis 01:12:17.59 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis 01:12:17.60

/opt/bitnami/scripts/redis/entrypoint.sh: line 26: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]

### What do you see instead?

After deploying pods on k8s from the image bitnami/redis it gives me error

/opt/bitnami/scripts/redis/entrypoint.sh: line 26: exec: --: invalid option

### Additional information

After deploying pods on k8s from the image bitnami/redis it gives me error

/opt/bitnami/scripts/redis/entrypoint.sh: line 26: exec: --: invalid option

**Comment by javsalgar** [comment]
Hi,

Did you perform any change in the chart values? We would like to reproduce the issue in our side.
