### ISSUE TITLE
REDIS_TLS_KEY_FILE -> Password Variable?

### ISSUE THREAD

**Issue by gleupold** [bitnami/bitnami-docker-redis#250]
### Name and Version

bitnami:redis:7.0.1

### What is the problem this feature will solve?

TLS: Adding Option to submit a passphrase for keyfile.

### What is the feature you are proposing to solve the problem?

TLS: keyfiles with passphrase.

### What alternatives have you considered?

TLS certificates without key passphrases.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! Could you please elaborate a bit more in the use case and what environment variable or files you expect as part of the feature?

**Comment by gleupold** [comment]
Hi @javsalgar ,

we have private key for the certificate which is secured by a passphrase. Maybe i am blind but i didnt find the Environment Variable which i should have used for that.

We use within docker compose following config:

`version: '3.6'

services:
  redis-server:
    restart: always
    environment:
      REDIS_REPLICATION_MODE: ${_REDIS_REPLICATION_MODE}
      REDIS_MASTER_HOST: ${_REDIS_MASTER_HOST}
      REDIS_MASTER_PASSWORD: ${_REDIS_MASTER_PASSWORD}
      REDIS_PASSWORD: ${_REDIS_PASSWORD}
      REDIS_MASTER_SET: ${_REDIS_MASTER_SET}
      REDIS_REPLICA_IP: ${_REDIS_REPLICA_IP}
      REDIS_TLS_ENABLED: "yes"
      REDIS_TLS_PORT: 6379
      REDIS_TLS_CERT_FILE: "/certs/server.crt"
      REDIS_TLS_KEY_FILE: "/certs/server.key"
      REDIS_TLS_CA_FILE: "/certs/server.ca"
    container_name: ${_REDIS_SERVER_CONTAINER_NAME}
    hostname: ${_REDIS_SERVER_CONTAINER_NAME}
    network_mode: host
    image: 'bitnami/redis:7.0.1'
    volumes:
      - "/opt/redis/certs:/certs"

  redis-sentinel:
    restart: always
    environment:
      REDIS_MASTER_HOST: ${_REDIS_MASTER_HOST}
      REDIS_MASTER_PASSWORD: ${_REDIS_MASTER_PASSWORD}
      REDIS_SENTINEL_RESOLVE_HOSTNAMES: ${_REDIS_SENTINEL_RESOLVE_HOSTNAMES}
      REDIS_MASTER_SET: ${_REDIS_MASTER_SET}
      REDIS_REPLICA_IP: ${REDIS_REPLICA_IP}
    container_name: ${_REDIS_SENTINEL_CONTAINER_NAME}
    hostname: ${_REDIS_SENTINEL_CONTAINER_NAME}
    network_mode: host
    image: 'bitnami/redis-sentinel:7.0.1'`

The log looks like this:
`
1:C 24 Jun 2022 14:06:15.227 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 24 Jun 2022 14:06:15.227 # Redis version=7.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 24 Jun 2022 14:06:15.227 # Configuration loaded
1:M 24 Jun 2022 14:06:15.227 # Failed to load private key: /certs/server.key: error:0907B068:PEM routines:PEM_read_bio_PrivateKey:bad password read
1:M 24 Jun 2022 14:06:15.227 # Failed to configure TLS. Check logs for more info.
redis 14:06:28.14
redis 14:06:28.14 Welcome to the Bitnami redis container
redis 14:06:28.14 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis 14:06:28.14 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis 14:06:28.15
redis 14:06:28.15 INFO  ==> ** Starting Redis setup **
redis 14:06:28.16 INFO  ==> Initializing Redis
redis 14:06:28.17 INFO  ==> Setting Redis config file
redis 14:06:28.21 INFO  ==> Configuring replication mode
redis 14:06:28.23 INFO  ==> ** Redis setup finished! **

redis 14:06:28.24 INFO  ==> ** Starting Redis **
1:C 24 Jun 2022 14:06:28.249 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 24 Jun 2022 14:06:28.249 # Redis version=7.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 24 Jun 2022 14:06:28.249 # Configuration loaded
1:M 24 Jun 2022 14:06:28.250 # Failed to load private key: /certs/server.key: error:0907B068:PEM routines:PEM_read_bio_PrivateKey:bad password read
1:M 24 Jun 2022 14:06:28.250 # Failed to configure TLS. Check logs for more info.
`
I would expect an environment variable to serve the passphrase to redis for the private key. When i am not totally wrong, this exists in the kubernetes version with:
https://docs.bitnami.com/kubernetes/infrastructure/redis/administration/enable-tls/
"tls.certificatesSecret="certificates-tls-secret"

**Comment by jotamartos** [comment]
Hi @gleupold,

Sorry for the delay and thank you for taking the time to suggest this update in our solution. We created a task on our side to include this option in our container so you can use it in the future. In the meantime, you can mount your own redis.conf file (you can copy it from the default one we generate) and configure your cert key in that file. Once Redis uses the new conf file you mounted, it should make use of the certificate without problems.

https://github.com/bitnami/bitnami-docker-redis#configuration-file

I hope this helps!

**Comment by carrodher** [comment]
I just added the _on-hold_ label to prevent the stale bot from closing this issue while we work on the task; depending on other priorities, issues, and bugs we are working on, we can provide an ETA for when this task can be completed.

**Comment by gleupold** [comment]
@carrodher : Thank you so much! I will try the workarround :)

**Comment by jotamartos** [comment]
Hi, 

You can set the `tls-key-file-pass` parameter in the Redis' configuration

https://github.com/redis/redis/blob/7.0/redis.conf#L207

**Comment by gleupold** [comment]
@jotamartos  : Thank you, i missed that and i will use it.

**Comment by corico44** [comment]
Hi!

We just released a new revision of the container. Now, we have an environment variable to set the passphrase for keyfile.

I think this should cover your use case! 😄
