### ISSUE TITLE
Why using gcr.io/stacksmith-images/ubuntu:14.04-r8 ?

### ISSUE THREAD

**Issue by phlegx** [bitnami/bitnami-docker-redis#33]
Hey there!

Why is there not used an ordinary official docker ubuntu image for  this redis image, if I may ask?

Is there a special reason for it? In my eyes using an official image would increase the trust in this image!

best
M

**Comment by prydonius** [comment]
Hey @phlegx! We needed to extend the official Ubuntu image to include the tooling for installing Bitnami packages. You can find the Dockerfile here: https://github.com/bitnami/stacksmith-base/blob/master/ubuntu/14.04/Dockerfile, and the other resources used are in that repository.

The Redis Dockerfile pulls in packages using the [bitnami-pkg](https://github.com/bitnami/stacksmith-base/blob/master/rootfs/usr/local/bin/bitnami-pkg) tool. These packages are installed and configured with the Nami tool (https://github.com/bitnami/nami) previously codenamed harpoon, which we open sourced.

I hope this explanation increases your trust in this image, let us know if you have any other questions!

**Comment by phlegx** [comment]
Thanks for the explanation! I now also just realized that **Bitnami** itself is something quite official and open source :-)
