### ISSUE TITLE
Set appendonly mode via docker ENV variables

### ISSUE THREAD

**Issue by phlegx** [bitnami/bitnami-docker-redis#37]
I'm wondering How are the options set here in the redis.conf file?

It would be very nice if one could set the the `appendonly` mode also via docker ENV variables. It would actually only require to set `appendonly no` to `appendonly yes` and the mode is enabled.

thanks

**Comment by sameersbn** [comment]
Hello @phlegx. You would need to edit [configuration](https://github.com/bitnami/bitnami-docker-redis#configuration-file) file as we currently do not expose any parameters to configure it.

**Comment by phlegx** [comment]
Hi @sameersbn! Thanks, Ok I see I have to do this manually. Would be cool if at some point this would work also by settingthe parameter as an ENV variable. Especially for example this setting is a one liner, so it would be implemented quite fast.

**Comment by phlegx** [comment]
@sameersbn hi! I just saw that it is also possible to SET the appendonly option trough redis console:

```
127.0.0.1:6379> config get appendonly
1) "appendonly"
2) "yes"
```

**Comment by sameersbn** [comment]
@phlegx Thats great. I wasn't aware of that. It's definitely the preferred way of specifying the configuration over manually editing the config files.  Thanks for sharing.
