### ISSUE TITLE
Sentinel support

### ISSUE THREAD

**Issue by Nepoxx** [bitnami/bitnami-docker-redis#53]
Having a "sentinel" mode passable to the environment variable would be very useful. Sentinels will automatically elect a new master shall the current one die.

**Comment by prydonius** [comment]
Thanks @Nepoxx 

cc @sameersbn @jloramas

**Comment by rasekar2000** [comment]
Looking forward this feature. Once ready can we have Helm with Redis Sentinel on https://kubeapps.com/charts/stable/redis
