### ISSUE TITLE
Feature request: Enable FLUSHDB/FLUSHALL via ENV variable

### ISSUE THREAD

**Issue by dmhendricks** [bitnami/bitnami-docker-redis#78]
**Description**

I create bitnami/redis containers for several WordPress sites (password protected, each dite giving its own bitnami/Redis container/port/password).

It would be nice if I could enable `FLUSHDB` and `FLUSHALL` by passing an -e flag instead of [having to edit](https://docs.bitnami.com/virtual-machine/infrastructure/redis/#security-information) /bitnami/redis/conf/redis.conf.

**Steps to reproduce the issue:**

1. Create bitnami/redis container.
2. Connect via your favorite client.
3. `redis-cli -h 127.0.0.1 -p 55301 -a MyCleverPassword`
4. `FLUSHDB`

**Describe the results you received:**

`(error) ERR unknown command 'FLUSHDB'`

**Describe the results you expected:**

`OK`

**Additional information you deem important:**

Since these instances are password protected, are provisioned privately for each client and the ports are firewalled off, I don't see the security issue with allowing the option (particularly since this is used for caching, so if an intruder did FLUSHDB, it would be the least of my problems.)

Perhaps I am mistaken.

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 32
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-65-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: node01.cloudverve.com
ID: CREF:EWUI:E3KG:SVAF:RHJX:Q3YO:EQXX:BLLL:A3QI:6JRQ:4QSG:KCVH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details:**

Though irrelevant to this request, you can use it for demographics:

- redis-cli: 3.0.6
- Host: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-65-generic x86_64) + KernelCare
- Stock Xenial `/etc/apt/sources.list`
- Nginx proxying LAMP, WordPress latest (4.7.3 currently) with latest [Redis Object Cache](https://wordpress.org/plugins/redis-cache/) to this issue, PECL Redis Extension 3.1.1

- Output of `kcarectl --info`:

```
kpatch-state: patch is applied
kpatch-for: Linux version 4.4.0-65-generic (buildd@lgw01-12) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #86-Ubuntu SMP Thu Feb 23 17:49:58 UTC 2017
kpatch-build-time: Wed Mar 15 17:15:30 2017
kpatch-description: 4;4.4.0-67.88
```

**Comment by silviofdez** [comment]
Thanks for your feedback, we are going to check if include these configuration via ENV vars could fit in our current approach.

**Comment by Kalyse** [comment]
Did this get added?

**Comment by silviofdez** [comment]
Our Engineering team has not worked yet on this task. I am afraid that I cannot provide you with an ETA.

**Comment by jar349** [comment]
The kubernetes helm chart uses the docker image built from this repository.  Our django app sometimes wants to [clear its cache](https://docs.djangoproject.com/en/2.0/topics/cache/#basic-usage) which ends up calling `FLUSHDB` when redis is the backing store.  The end result is that we can't use the kubernetes helm chart because it uses your docker image, which does not provide a way to enable the commands.

**Comment by andresbono** [comment]
Hi @dmhendricks, @Kalyse, @jar349 we have just updated the container to allow specifying the commands that should be enabled or disabled starting with the [4.0.8-r7](https://github.com/bitnami/bitnami-docker-redis/releases/tag/4.0.8-r7) release.

For more information about the usage of this feature, please check the [README.md: Disabling Redis commands](https://github.com/bitnami/bitnami-docker-redis/blob/master/README.md#user-content-disabling-redis-commands).

Thanks for suggesting this and also for your patience!

Regards,
-Andrés B.

**Comment by jar349** [comment]
@andresbono I recommend that you close this issue because it has been addressed.

**Comment by marcosbc** [comment]
Thanks @jar349! Closing it.
