### ISSUE TITLE
helm install --set persistence.enabled=false stable/redis

### ISSUE THREAD

**Issue by blackstar257** [bitnami/bitnami-docker-redis#81]
**Description**

```
Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing redis
Error executing 'postInstallation': EEXIST: file already exists, symlink '/opt/bitnami/redis/conf' -> '/opt/bitnami/redis/etc'

```
**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
 Kernel Version:		3.10.0-514.16.1.el7.x86_64
 OS Image:			CentOS Linux 7 (Core)
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.12.6
 Kubelet Version:		v1.6.1
 Kube-Proxy Version:		v1.6.1
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by prydonius** [comment]
Hey @blackstar257 - did you figure out the issue?

**Comment by blackstar257** [comment]
No it keeps happening whenever i do

```
redis:
  persistence:
    enabled: false
```

**Comment by sameersbn** [comment]
@blackstar257 could you please provide us some information about regarding your kubernetes setup which will help us understand and hopefully reproduce the issue you're seeing. 

How has the kubernetes cluster been setup? Are you using GKE, AWS, minikube, etc? If you're using minikube can you share the details of the platform (mac, linux, windows) and the minikube version in use? In case you're using minikube, please update to the latest release (0.18.0) and let us know if it resolves the issue.

Thanks.

**Comment by chipironcin** [comment]
Hi @blackstar257 
I was able to deploy Redis successfully in my GKE cluster using Helm with the command:
```
helm install --set persistence.enabled=false stable/redis
```

Also please provide the version of the chart you are using:
```
helm search stable/redis
```

**Comment by blackstar257** [comment]
It happens on a kubeadm kubernetes v1.6.1 setups.

**Comment by sameersbn** [comment]
@blackstar257 I noticed that you are using centos 7 for your nodes. Can you please check if docker has been configured to use the OverlayFS graph driver? If yes, then it is probably the cause of the issue. OverlayFS is marked as a preview filesystem and there are some measures you need to take for using OverlayFS. Please refer to the following link for additional details.

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

**Comment by blackstar257** [comment]
Looks like that's probably it! Thanks @sameersbn

**Comment by sameersbn** [comment]
thanks for the confirmation @blackstar257 and thanks for choosing Bitnami container images :+1:
