### ISSUE TITLE
Feature Request - RAM only and disable any redis persistence

### ISSUE THREAD

**Issue by rturk** [bitnami/bitnami-docker-redis#84]
Please clarify if its possible to run this image without any redis persistence, this means run the Redis Docker using solely RAM and most importantly without a volume.

If this is not possible please consider this as a feature request

**Comment by javsalgar** [comment]
Hi, 

Yes, you can run the redis container without any volumes if you want. The only consequence will be that, when the container is destroyed, so will be the data.

**Comment by prydonius** [comment]
The Dockerfile exports `/bitnami/redis` as a volume, so even if you don't mount any volumes you're still writing to disk in ephemeral volumes. To completely disable persistence in Redis the configuration would need to be modified (http://stackoverflow.com/questions/28785383/how-to-disable-persistence-with-redis). Perhaps an env var should be added to make that change?

Even with Redis persistence disabled though, unless the [VOLUME instruction](https://github.com/bitnami/bitnami-docker-redis/blob/master/3/Dockerfile#L19) in the Dockerfile is removed, Docker will always mount a volume at `/bitnami/redis` - however it just won't be used.

**Comment by rturk** [comment]
@prydonius tks. We've moved to the default redis image from Docker hub, it was easier to setup redis.conf using this image https://hub.docker.com/_/redis/
