### ISSUE TITLE
I have no name! // UID is not mapped to /etc/passwd inside container

### ISSUE THREAD

**Issue by qodeboy** [bitnami/bitnami-docker-redis#86]
**Description**

When executing bash in container, bash prompt says "I have no name!" instead of username in bash prompt, making bash behavior inconsistent (text overlaps when pasting, various glitches when typing, etc). 

**Steps to reproduce the issue:**

1. Launch container.

**Describe the results you received:**

Bash misbehaves.

**Describe the results you expected:**

UID is mapped to /etc/passwd. Bash working as expected. 

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens because of ```USER 1001``` in Dockerfile. This should be either remove or user with this UID should be created during build.

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:42:53 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 17
 Running: 14
 Paused: 0
 Stopped: 3
Images: 10
Server Version: 17.07.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 144
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.91GiB
Name: srv
ID: HMGW:37PF:RLAD:DY45:MSQI:6VZJ:MVMH:Z4D6:H7XF:DQK6:JV7U:Q5QE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.16.1, build 6d1ac219
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by qodeboy** [comment]
This could be workaround by adding ```--user``` if you run with docker run or ```user: bitnami``` if you use docker-compose.

**Comment by prydonius** [comment]
Hi @qodeboy,

The reason for this is to apply the best practices as enforced by the OpenShift environment (see "Supporting Arbitrary User IDs" in https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines).

Whilst the "I have no name!" looks strange, it shouldn't result in glitches in bash. Can you show an example of what you're seeing?

**Comment by VBoB13** [comment]
Since I also have the "I have no name!" too, I thought it'd be worth asking if it would have anything to do with the fact that I can't seem to even move files around within the container?
```
I have no name!@97010fd4cf49:/opt/bitnami/airflow/dags/dags$ mv lowi50.py ../lowi50.py
mv: cannot move 'lowi50.py' to '../lowi50.py': Permission denied
I have no name!@97010fd4cf49:/opt/bitnami/airflow/dags/dags$
```

Is this related or not?

**Comment by carrodher** [comment]
This is caused because the containers follow a non-root approach, which is a good practice in terms of security. You can find more info at https://docs.bitnami.com/tutorials/work-with-non-root-containers and/or https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/.

In those blog posts, you can find some tips to launch the container as a root user.
