### ISSUE TITLE
Error at the start of the container

### ISSUE THREAD

**Issue by R0binT** [bitnami/bitnami-docker-redis#91]
Hi all, here is my problem :

**Description**

I just pulled the last image of the container. When it start, it loop on the error : 
  
`Error executing 'postInstallation': Files to substitute resolved to an empty list`

I have actually 2 identical servers (both on coreos). On one the container start without problem, but not on the other.

I have a docker-compose (which is used on both servers).
[docker-compose.txt](https://github.com/bitnami/bitnami-docker-redis/files/1639279/docker-compose.txt)

**Steps to reproduce the issue:**

1. I launch my docker-compose
2. docker logs redis

**Describe the results you received:**

```
Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing redis
redis   INFO  ==> Validating inputs...
Error executing 'postInstallation': Files to substitute resolved to an empty list

```

**Version**

- Output of `docker version`:

```
Docker version 17.12.0-ce, build c97c6d6
```

- Output of `docker info`:

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.844GiB
Name: azmsnl-ap12.azure.cloud.corp.local
ID: WMJI:RVPA:YCB4:C575:COIP:CIZH:A7I4:SF7Y:XSEZ:5VE7:JJGW:XHRA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.10.0, build 4bd6f1a
docker-py version: 2.0.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

My servers are on Microsoft Azure

Thank you all for your help

**Comment by javsalgar** [comment]
Hi, 

Thanks for creating the case. I cannot reproduce the environment as there are files missing (the env files) and the third container image seems to be private. Could you adapt it so it is fully reproducible?

Thanks

**Comment by R0binT** [comment]
Hi,
I will try that

**Comment by R0binT** [comment]
Hi again,
So actually I tried to start only a container with redis.

So my yml looks like that : 
```
version: '3'
services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    restart: always
    env_file:
      - redis-prod.env
    ports:
      - '6380:6379'
    volumes:
      - /data/redis:/bitnami
```

the env file contain only the password. the line is : 
`REDIS_PASSWORD=rnZkVWf4,VPMlh^Ud63~oD6a`


so my commands is : 
`docker-compose -f ./redis-compose.yml up --build -d`

the container start correctly, but after something like 25 seconds, it crash.

still the same error : 
```

Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing redis
redis   INFO  ==> Validating inputs...
Error executing 'postInstallation': Files to substitute resolved to an empty list
```

**Comment by javsalgar** [comment]
Hi,

This is very strange, what could be the difference between each of the servers? Could it be a permissions issue with the mounted volumes? Have you tried removing the volumes and trying again?

**Comment by R0binT** [comment]
Hi,

There is absolutly no difference between both. They are on azure. Auto generated by azure. I did exactly the same thing for both :/

Yes I tried removing the volume, changing the path and stuff but nothing worked.

I was thinking maybe it is a problem with the server itself like a corrupted file or something from the install.

I agree it is very strange.

**Comment by zeusito** [comment]
Hi,

I think this issue applies only to the "latest" image, I was having the exact same error, then I pulled the "4.0" image and everything works ok. Using CentOS 7.4

**Comment by javsalgar** [comment]
@R0binT would changing the image tag in the "faulty" server do the trick? @zeusito which are the specs and environment of your machine?

**Comment by R0binT** [comment]
@javsalgar I will try that. But the weird thing is that I have the latest image on my both coreOs servers and only one fail :/

I will try that and come back to you

**Comment by zeusito** [comment]
I tested the "latest" image with debian and it worked without problems, tested again in another node running CentOS 7.4 and the problem was there (if no volume is mounted then the error does not appear).

Current Setup:
- CentOS 7.4
- Google could based VM
- Docker CE 17.09
- Docker Compose 1.17.0
- Using a mounted volume mapped to "/bitnami"

**Comment by javsalgar** [comment]
I was able to partially reproduce the issue in CentOS. The first time it failed because the volume had incorrect permissions.

```
[centos@ip-172-31-38-228 ~]$ docker-compose up
redis is up-to-date
Attaching to redis
redis    |
redis    | Welcome to the Bitnami redis container
redis    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis    | Send us your feedback at containers@bitnami.com
redis    |
redis    | nami    INFO  Initializing redis
redis    | redis   INFO  ==> Validating inputs...
redis    | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis'
```

 I changed the permissions (777 for testing) and then the substitute issue appeared. 

```
redis    | Welcome to the Bitnami redis container
redis    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis    | Send us your feedback at containers@bitnami.com
redis    |
redis    | nami    INFO  Initializing redis
redis    | redis   INFO  ==> Validating inputs...
redis    | Error executing 'postInstallation': Files to substitute resolved to an empty list
```

Then I executed docker-compose down and up (and removed the volume content) and the issue was gone.

```
[centos@ip-172-31-38-228 ~]$ docker-compose up
Creating network "centos_default" with the default driver
Creating redis ... done
Attaching to redis
redis    |
redis    | Welcome to the Bitnami redis container
redis    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis    | Send us your feedback at containers@bitnami.com
redis    |
redis    | nami    INFO  Initializing redis
redis    | redis   INFO
redis    | redis   INFO  ########################################################################
redis    | redis   INFO   Installation parameters for redis:
redis    | redis   INFO     Persisted data and properties have been restored.
redis    | redis   INFO     Any input specified will not take effect.
redis    | redis   INFO   This installation requires no credentials.
redis    | redis   INFO  ########################################################################
redis    | redis   INFO
redis    | nami    INFO  redis successfully initialized
redis    | INFO  ==> Starting redis...
redis    | 28:C 23 Jan 12:01:08.167 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis    | 28:C 23 Jan 12:01:08.167 # Redis version=4.0.6, bits=64, commit=00000000, modified=0, pid=28, just started
redis    | 28:C 23 Jan 12:01:08.167 # Configuration loaded
```

**Comment by R0binT** [comment]
Ha great thanks a lot
I gonna try that and let you know asap

**Comment by javsalgar** [comment]
Cool, let us know what you see :)

**Comment by javsalgar** [comment]
@hesj I did not change the file AFAIK

**Comment by syst0m** [comment]
I am experiencing the same issue, while trying to run on bare metal, Ubuntu 16.04.3.
Not using persistence, so not using volumes.

```
# docker --version
Docker version 1.13.1, build 092cba3
```
```
# docker-compose --version
docker-compose version 1.8.0, build unknown
```
```
# uname -a
Linux comprigo-staging3 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
# docker-compose up redis-master redis-slave 
Starting dockerpublisherapi_redis-master_1
Starting dockerpublisherapi_redis-slave_1
Attaching to dockerpublisherapi_redis-master_1, dockerpublisherapi_redis-slave_1
redis-master_1  | 
redis-master_1  | Welcome to the Bitnami redis container
redis-slave_1   | 
redis-master_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis-slave_1   | Welcome to the Bitnami redis container
redis-master_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis-master_1  | Send us your feedback at containers@bitnami.com
redis-slave_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis-slave_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis-slave_1   | Send us your feedback at containers@bitnami.com
redis-slave_1   | 
redis-master_1  | 
redis-master_1  | INFO  ==> Starting redis... 
redis-master_1  | 21:C 06 Apr 20:21:30.463 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-master_1  | 21:C 06 Apr 20:21:30.463 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=21, just started
redis-master_1  | 21:C 06 Apr 20:21:30.463 # Configuration loaded
redis-master_1  |                 _._                                                  
redis-master_1  |            _.-``__ ''-._                                             
redis-master_1  |       _.-``    `.  `_.  ''-._           Redis 4.0.9 (00000000/0) 64 bit
redis-master_1  |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis-master_1  |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis-master_1  |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis-master_1  |  |    `-._   `._    /     _.-'    |     PID: 21
redis-master_1  |   `-._    `-._  `-./  _.-'    _.-'                                   
redis-master_1  |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis-master_1  |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis-master_1  |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis-master_1  |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis-master_1  |  |    `-._`-._        _.-'_.-'    |                                  
redis-master_1  |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis-master_1  |       `-._    `-.__.-'    _.-'                                       
redis-master_1  |           `-._        _.-'                                           
redis-master_1  |               `-.__.-'                                               
redis-master_1  | 
redis-master_1  | 21:M 06 Apr 20:21:30.464 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis-master_1  | 21:M 06 Apr 20:21:30.464 # Server initialized
redis-master_1  | 21:M 06 Apr 20:21:30.464 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis-master_1  | 21:M 06 Apr 20:21:30.464 * Ready to accept connections
redis-slave_1   | nami    INFO  Initializing redis
redis-slave_1   | redis   INFO  ==> Validating inputs...
redis-slave_1   | Error executing 'postInstallation': Files to substitute resolved to an empty list
dockerpublisherapi_redis-slave_1 exited with code 1
```

**Comment by syst0m** [comment]
Tried configuring a volume. Now I get:

```
redis-slave_1   | nami    INFO  Initializing redis
redis-slave_1   | redis   INFO  ==> Validating inputs...
redis-slave_1   | redis   INFO  ==> Configuring replication settings...
redis-slave_1   | redis   INFO  ==> Checking if master is ready to accept connection...

redis-master_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis'
```

docker-compose.yaml excerpt:

```
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=saeviyeeM7Xohlengi5o
    volumes:
      - '/redis:/bitnami'

```

**Comment by javsalgar** [comment]
Hi,

Did you check this comment? I was a able to partially reproduce the issue

https://github.com/bitnami/bitnami-docker-redis/issues/91#issuecomment-359769908

**Comment by syst0m** [comment]
Hi,

yeah, that seems to work.

**Comment by javsalgar** [comment]
Awesome! Thanks for letting us know

**Comment by aneshranjit** [comment]
Hi @syst0m 

I'm facing the similar error you faced.

`redis_1     |
redis_1     | Welcome to the Bitnami redis container
redis_1     | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis_1     | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis_1     |
redis_1     | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis_1     | nami    INFO  Initializing redis
redis_1     | redis   INFO
redis_1     | redis   INFO  ########################################################################
redis_1     | redis   INFO   Installation parameters for redis:
redis_1     | redis   INFO     Persisted data and properties have been restored.
redis_1     | redis   INFO     Any input specified will not take effect.
redis_1     | redis   INFO   This installation requires no credentials.
redis_1     | redis   INFO  ########################################################################
redis_1     | redis   INFO
redis_1     | nami    INFO  redis successfully initialized
redis_1     | INFO  ==> Starting redis...
redis_1     | 28:C 16 May 03:28:13.023 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 28:C 16 May 03:28:13.023 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=28, just started
redis_1     | 28:C 16 May 03:28:13.023 # Configuration loaded
redis_1     |                 _._
redis_1     |            _.-``__ ''-._
redis_1     |       _.-``    `.  `_.  ''-._           Redis 4.0.9 (00000000/0) 64 bit
redis_1     |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1     |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1     |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1     |  |    `-._   `._    /     _.-'    |     PID: 28
redis_1     |   `-._    `-._  `-./  _.-'    _.-'
redis_1     |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1     |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1     |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1     |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1     |  |    `-._`-._        _.-'_.-'    |
redis_1     |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1     |       `-._    `-.__.-'    _.-'
redis_1     |           `-._        _.-'
redis_1     |               `-.__.-'
redis_1     |
redis_1     | 28:M 16 May 03:28:13.024 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 28:M 16 May 03:28:13.024 # Server initialized
redis_1     | 28:M 16 May 03:28:13.024 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.`

 and I'm having difficulty disabling THP.
Could you please tell me how you did it step by step?
I'm new to using docker.

**Comment by javsalgar** [comment]
Hi,

This looks like a different issue to me. When working with containers, the OS kernel they use is the same as the host system. Therefore (without using docker), you would need to execute this:

```
sudo su
echo never > /sys/kernel/mm/transparent_hugepage/enabled
```

**Comment by btomala** [comment]
I have the same issue on my local machine, I try this https://github.com/bitnami/bitnami-docker-redis/issues/91#issuecomment-359769908, but after the third step, I got the same error which I get in the second one.

```
$ docker --version
Docker version 18.05.0-ce, build f150324782
$ docker-compose --version
docker-compose version 1.21.2, build unknown
$ uname -a
Linux latitude 4.17.4-1-MANJARO #1 SMP PREEMPT Tue Jul 3 18:11:09 UTC 2018 x86_64 GNU/Linux
```

**Comment by javsalgar** [comment]
Hi,

Could you try removing the content of the persisted folder (maintaining the permissions) and try again?

**Comment by btomala** [comment]
This didn't help, but today when I turn on my machine and try it one more time it starts working.

**Comment by javsalgar** [comment]
Hi,

That is weird, so now you are unable to reproduce the steps to the issue?

**Comment by btomala** [comment]
Hi, Correct I'm unable to reproduce the issue. 

I think changing rights to a directory on the host helps.
I applied the command `chmod 777 redis-data/` before a restart.

But now when I'm changing them back to 776 i get different error 
> redis_1    | 22:C 11 Jul 09:52:15.214 # Can't chdir to '/opt/bitnami/redis/data': Permission denied

**Comment by javsalgar** [comment]
Could you check the ownership as well? Just in case

**Comment by btomala** [comment]
I'm the owner of `redis-data` directory 
```ls -la 
drwxrwxrwx  3 bartek   bartek  4096 07-10 09:31 redis-data
```
```ls -la redis-data
drwxr-xr-x  4   1001 root   4096 07-10 09:32 redis
```

Who is the uid 1001?

**Comment by javsalgar** [comment]
The uid 1001 is the one that executes the processes (as it is a non-root container). This 1001 user belongs to the root group. When using mounted directory it can be a bit frustrating because OSes behave differently.
