### ISSUE TITLE
Rejson image

### ISSUE THREAD

**Issue by bhack** [bitnami/bitnami-docker-redis#92]
Can you support Rejson [image variant](https://github.com/RedisLabsModules/rejson)?
This generate `redislabs/rejson:latest` on dockerhub.

**Comment by javsalgar** [comment]
Hi,

Thanks for opening the issue. It looks interesting, so I will forward this to the rest of the team. We will evaluate adding the extension to the image. I cannot guarantee an ETA, but if there are advances on it, we will let you know :)

**Comment by bhack** [comment]
@javsalgar Thanks, in the meantime can your official Helm/Chart image work on the dockerhub upstream dockerhub `redislabs/rejson:latest`?

**Comment by bhack** [comment]
I suppose that I will lose only `REDIS_PASSWORD` env is it right?

**Comment by bhack** [comment]
See also https://github.com/docker-library/redis/issues/46. Could be useful to sync consumed env with the official one.

**Comment by javsalgar** [comment]
Hi,

Our Helm charts are meant to work with the Bitnami containers we create. I do not know if using that image will be compatible with the chart. In any case, there are no plans on supporting other non-bitnami containers in our charts.

**Comment by bhack** [comment]
Yes it doesn't work on the shelf and It need some hacks in values.yaml. But actually it is the only solution to have a REJSON module quickly without customizing the image. 
Of course we are loosing `REDIS_PASSWORD`. 
I've opened an upstream issue at https://github.com/RedisLabs/DockerHub/issues/10 in the hope that they want to be more involved. /cc @redislabs

**Comment by bhack** [comment]
Is there a way to contribute this module to the bitnami redis package?

**Comment by bhack** [comment]
@javsalgar I have a bad hack that works but I want to have feedback for a better integration:
```diff
--- a/4.0/Dockerfile
+++ b/4.0/Dockerfile
@@ -1,5 +1,7 @@
+FROM redislabs/rejson:latest as rejson
 FROM bitnami/minideb-extras:jessie-r22
 LABEL maintainer "Bitnami <containers@bitnami.com>"
+COPY --from=rejson /usr/lib/redis/modules/rejson.so /usr/local/lib/rejson.so
 
 ENV BITNAMI_PKG_CHMOD="-R g+rwX" \
     HOME="/"
```

**Comment by javsalgar** [comment]
Thanks for sharing your solution. From what I see, what it makes more sense to me is to compile the `rejson.so` file and include it in the redis package that is downloaded in `bitnami-pkg`. I think that this current hack may work for the time being.

**Comment by bhack** [comment]
@javsalgar I cannot PR bitnami-pkg right? So what we could do?

**Comment by javsalgar** [comment]
At the moment, while we consider adding this to our official container, you can use your forked container

https://github.com/bitnami/bitnami-docker-redis/issues/92#issuecomment-387036095

If, in the end, we add the extension to the container, we will let you know

**Comment by prydonius** [comment]
There is a PR in the helm/charts repository that has some good feedback around the general issue of adding modules to the bitnami/redis image:

helm/charts#7745 (@jlegrone)

> That said, currently in order to create a custom redis image (to add redis modules, build off a different base image, etc) that is compatible with this chart, reverse engineering what is going on in the bitnami/redis image and building most of that functionality into the customized image is necessary. This is a non-trivial task and the root of what I'm attempting to improve upon in this PR.

What can we do to make this easier?

**Comment by javsalgar** [comment]
I suppose that we could either:

- Be able to mount external modules to be added to redis (provided they are compiled using a compatible OS)
- Have an easy way to make users build their own images with the modules they want (maybe using blacksmith?)

**Comment by bhack** [comment]
I think that this could be a more general problem related to modular software especially for not interpreted languages then needs ABI compatibility. So I think that if we can find a solution for this we can solve also for other cases.

**Comment by javsalgar** [comment]
To my mind, the easiest choice is to have the same environment where we compile redis available for compiling other assets. We use blacksmith for compiling the assets, and minideb-extras for building Redis.

https://github.com/bitnami/blacksmith

So the best choice would be to use it to build the modules and then mount them in the image.

**Comment by andywatts** [comment]
I copied rejson.so from the RedisJson docker image and to a running Bitnami/redis container.
`ldd rejson.so` shows it's just linked to standard libs, so works just fine.


From redis console, run "LOAD MODULE /opt/bitnami/redis/rejson.so".

The below then works just fine...
JSON.SET obj . '{"name":"Leonard Cohen","lastSeen":1470,"loggedOut": true}'
JSON.GET obj name

I'm wondering how to automate the copy and load.  
Ideally in bitnami/red-is helm chart values...

Any chance we could include rejson.so in the bitnami/redis image?

**Comment by javsalgar** [comment]
Hi,

It is still in our backlog. I will check if we can re-evaluate and re-prioritize.

**Comment by andywatts** [comment]
I put the module on my persistent data volume and load from there.  Works well enough.

**Comment by javsalgar** [comment]
Good to know that there is a workaround for the time being :)

**Comment by h0tw4t3r** [comment]
> Thanks for sharing your solution. From what I see, what it makes more sense to me is to compile the `rejson.so` file and include it in the redis package that is downloaded in `bitnami-pkg`. I think that this current hack may work for the time being.

Any updates on this?

**Comment by javsalgar** [comment]
Right now there are no short-term plans on adding rejson.so. Could you explain your use case?

**Comment by bhack** [comment]
@h0tw4t3r You can ask to https://github.com/harsh4870/Redis-Rejson-HA-Helm-Chart author if he want to contribute it to the new Helm Hub repo.

**Comment by matth-c3** [comment]
Hello, 

I was having the same issue but I did not want to build my own image to not have to keep track of the latest version available.

If you are using the Helm Chart to deploy redis/redis cluster, you can use the parameters `master.preExecCmds` and `replica.preExecCmds` to download the rejson module before `redis` start ( from s3 or azure blob storage )

Then you can use the following parameter to load the module when redis-server start 

- `master.args='["--loadmodule /path/where/you/download/the/rejson/lib"]'` for the master 
- `replica.args='["--loadmodule /path/where/you/download/the/rejson/lib"]'` for the replica

**Comment by javsalgar** [comment]
Thanks for the tip! We wanted to add customization in the helm chart to cover use cases like these.

**Comment by adamwoolhether** [comment]
> Hi,
> 
> I'm not sure I understood correctly, are you using the redis/rejson image in the chart instead of the bitnami/redis image?

Yes, i've set the values `image.repository=redislabs/rejson,image.tag=2.0.0` to use the official RedisLabs image with the module included, to avoid having to manually load/install the module. Doing so, you can't use the `master.args` values.

Here's what did work for me, is setting the `master.extraFlags` value, for example:
```
helm install qbatch-redis bitnami/redis --set master.service.port=6380,image.repository=redislabs/rejson,image.tag=2.0.0,master.extraFlags='{--loadmodule /usr/lib/redis/modules/rejson.so}'
```

This is much simpler and still allows full configuration via other Helm chart values.

**Comment by hansehe** [comment]
> > Hi,
> > I'm not sure I understood correctly, are you using the redis/rejson image in the chart instead of the bitnami/redis image?
> 
> Yes, i've set the values `image.repository=redislabs/rejson,image.tag=2.0.0` to use the official RedisLabs image with the ReJSON module included, to avoid manual loading/installing the module. Doing so, using the `master.args` values does not work.
> 
> Here's **what did work for me**, is setting the `master.extraFlags` value, for example:
> 
> ```
> helm install my-redis bitnami/redis --set image.repository=redislabs/rejson,image.tag=2.0.0,master.extraFlags='{--loadmodule /usr/lib/redis/modules/rejson.so}'
> ```
> 
> This is much simpler and still allows full configuration via other Helm chart values.

Just for the record, you should also use this flag under the replica section, as such:
```yaml
redis:
    image:
        repository: redislabs/rejson
        tag: 2.0.6
    master:
        extraFlags: 
            - --loadmodule /usr/lib/redis/modules/rejson.so
    replica:
        extraFlags: 
            - --loadmodule /usr/lib/redis/modules/rejson.so
        replicaCount: 3
    auth:
        password: redis
```

**Comment by IreneGhafari-TomTom** [comment]
Hello,

If I try to load the module from `redislabs/rejson:latest`, it will fail because the bitnami image is based on debian buster, but the rejson module is created on debian bullseye. how did you guys tackle this?
