### ISSUE TITLE
Default args / REDIS_EXTRA_FLAGS aren't passed to redis command

### ISSUE THREAD

**Issue by niels-s** [bitnami/bitnami-docker-redis#93]
**Description**

We ran into issues where our append only file for redis was growing to big and started to fill the disk. When investigating we noticed `auto-aof-rewrite-percentage` nor `auto-aof-rewrite-min-size` was configured for our redis server ( checked using redis-cli: `redis-cli get auto-aof-rewrite-percentage`) When I tried to pass these configuration as `REDIS_EXTRA_FLAGS` like implemented [here](https://github.com/bitnami/bitnami-docker-redis/commit/07c42bf3999fd0eb982596cbb21fa9bc6024d4ad), I noticed these aren't passed to the redis-server command like they should according to the referred changes. After further investigation I noticed the default arguments from the `/run.sh` file aren't used either so the default values from the `/opt/bitnami/redis/conf/redis.conf` config file aren't used which could have prevented our issue as well. Basically these are 2 issues, 1 default args from `/run.sh` aren't passed and 2 the `REDIS_EXTRA_FLAGS` aren't passed but afaik I think these 2 are related.

**Steps to reproduce the issue:**

1. `export ID=$(docker run -ti -d --env="ALLOW_EMPTY_PASSWORD=yes" bitnami/redis:4.0)`
2. `docker exec $ID ps -ef`

**Describe the results you received:**

With the `ps -ef` command you will notice that the redis-server command is started with only `0.0.0.0:6379` as argument 

**Describe the results you expected:**

I expected the redis-server to start with the arguments `/opt/bitnami/redis/conf/redis.conf --daemonize no` like specified in the `/run.sh` file and the `REDIS_EXTRA_FLAGS` to be passed also. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

- Output of `docker info`:

```
Containers: 11
 Running: 2
 Paused: 0
 Stopped: 9
Images: 39
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 105
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 4W4N:KL5W:GKJE:AS5R:UMM7:AWGX:H5ZR:QDW6:QA3D:GUUS:JOLK:EEUZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 42
 Goroutines: 72
 System Time: 2018-02-05T16:59:31.907761238Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):*

**Comment by jotadrilo** [comment]
Hello @niels-s,

I tried to reproduce your issue and this is what I got:

I ran `/run.sh` in debug mode and I see the `--daemonize no` option is getting passed. However, the `ps` command does not show this:

```
jotadrilo ~ » export ID=$(docker run -ti -d --env="ALLOW_EMPTY_PASSWORD=yes" bitnami/redis:4.0 /bin/bash)

jotadrilo ~ » docker exec -it $ID bash

I have no name!@248a27be2317:/$ /app-entrypoint.sh /run.sh
# Ctrl-C once ready

I have no name!@248a27be2317:/$ bash -x /run.sh
...
+ EXEC=/opt/bitnami/redis/bin/redis-server
+ ARGS='/opt/bitnami/redis/conf/redis.conf --daemonize no'
+ [[ -n '' ]]
+ sed -i 's/^logfile /# logfile /g' /opt/bitnami/redis/conf/redis.conf
+ '[' 1001 -eq 0 ']'
+ exec /opt/bitnami/redis/bin/redis-server /opt/bitnami/redis/conf/redis.conf --daemonize no
106:C 06 Feb 10:50:27.326 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
106:C 06 Feb 10:50:27.326 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=106, just started
```

Actually, you can verify the `daemonize` option is properly parsed by Redis:

```
jotadrilo ~ » docker exec -it -u 0 $ID bash

root@4781f44809b0:/# COLUMNS=10000 ps -auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
...
1001        93  0.0  0.1  20252  3268 pts/2    Ss   10:49   0:00 bash
1001       106  0.1  0.2  41644  4204 pts/2    Sl+  10:50   0:00  \_ /opt/bitnami/redis/bin/redis-server 0.0.0.0:6379

root@4781f44809b0:/# redis-cli
127.0.0.1:6379> config get daemonize
1) "daemonize"
2) "no"
```

If you use the `REDIS_EXTRA_FLAGS` env var:

```
jotadrilo ~ » export ID=$(docker run -ti -d --env="ALLOW_EMPTY_PASSWORD=yes" --env="REDIS_EXTRA_FLAGS=--maxmemory 100mb" bitnami/redis:4.0 /bin/bash)

jotadrilo » docker exec -it $ID bash

I have no name!@54aff4611315:/$ /app-entrypoint.sh /run.sh
# Ctrl-C once ready

I have no name!@54aff4611315:/$ bash -x /run.sh
...
+ EXEC=/opt/bitnami/redis/bin/redis-server
+ ARGS='/opt/bitnami/redis/conf/redis.conf --daemonize no'
+ [[ -n --maxmemory 100mb ]]
+ ARGS+=' --maxmemory 100mb'
+ sed -i 's/^logfile /# logfile /g' /opt/bitnami/redis/conf/redis.conf
+ '[' 1001 -eq 0 ']'
+ exec /opt/bitnami/redis/bin/redis-server /opt/bitnami/redis/conf/redis.conf --daemonize no --maxmemory 100mb
52:C 06 Feb 11:19:47.063 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
52:C 06 Feb 11:19:47.064 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=52, just started
```

```
root@54aff4611315:/# COLUMNS=10000 ps -auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        62  0.0  0.1  20248  3220 pts/2    Ss   11:21   0:00 bash
root        68  0.0  0.0  17496  1988 pts/2    R+   11:21   0:00  \_ ps -auxf
1001        13  0.0  0.1  20252  3252 pts/1    Ss   11:17   0:00 bash
1001        52  0.1  0.2  41644  4100 pts/1    Sl+  11:19   0:00  \_ /opt/bitnami/redis/bin/redis-server 0.0.0.0:6379

root@54aff4611315:/# redis-cli
127.0.0.1:6379> config get daemonize
1) "daemonize"
2) "no"
127.0.0.1:6379> config get maxmemory
1) "maxmemory"
2) "104857600"
```

For some reason, the command in `ps` does not show this information but it seems to be fine with the client.

Did you notice some option is not properly set with `REDIS_EXTRA_FLAGS`?

I hope it helps!

**Comment by jotadrilo** [comment]
I've just noticed a typo in your message (`redis-cli get auto-aof-rewrite-percentage`). Please note the difference:

```
root@54aff4611315:/# redis-cli get auto-aof-rewrite-percentage
(nil)
root@54aff4611315:/# redis-cli config get auto-aof-rewrite-percentage
1) "auto-aof-rewrite-percentage"
2) "100"
```

**Comment by niels-s** [comment]
@jotadrilo you are right, I made a typo with the config command. Sorry I wasted your time.
I've checked it locally If I was able to pass extra flags using the `REDIS_EXTRA_FLAGS` env var, that worked out fine when I checked it using the correct `config` command.

Thanks for looking into it!
